anagram/build/.gitignore, anagram/project.yml, anagram/rakefile.rb, anagram/src/anagram.h, anagram/src/example.c, anagram/test/test_anagram.c, config.json
Added all the tests except for the unicode ones. I could add unicode support, but I'd probably have to include a small utf8 library that people could use.
=> Added the anagram exercise.

SETUP.md
Presumes #12 has been merged in.
Requires this page to exist: http://help.exercism.io/getting-started-with-c.html
=> Add SETUP.md

exercises/leap/test/test_leap.c
Very minor change so that while running the tests the correct test file is named.
=> leap: Corrected where test says it is running from

config.json, exercises/hello-world/makefile, exercises/hello-world/src/example.h, exercises/hello-world/test/test_hello_world.c, exercises/hello-world/test/vendor/unity.c, exercises/hello-world/test/vendor/unity.h, exercises/hello-world/test/vendor/unity_internals.h
Added the hello-world exercise, based upon examples in other tracks.
Sorry for the multiple commits! I was trying to squash by using a different branch but it seems that didn't go to plan.
=> hello-world: Added hello-world exercise

SETUP.md
=> Capitalize 'Exercism'

config.json
=> Updated config.json to match new specification

exercises/grains/src/example.c
=> Use C99 style in grains example

config.json, exercises/pangram/makefile, exercises/pangram/src/example.c, exercises/pangram/src/example.h, exercises/pangram/test/test_pangram.c, exercises/pangram/test/vendor/unity.c, exercises/pangram/test/vendor/unity.h, exercises/pangram/test/vendor/unity_internals.h
This will probably need to be updated depending on the outcome of #52 and #53
=> Add pangram exercise

exercises/hello-world/src/example.c, exercises/hello-world/src/example.h, exercises/hello-world/src/hello_world.c, exercises/hello-world/src/hello_world.h, exercises/hello-world/test/test_hello_world.c
Closes #33 
Closes #43 
Closes #56
=> Use NULL instead of empty string when no name is provided

.travis.yml, README.md, bin/verify-indent, exercises/anagram/src/anagram.h, exercises/anagram/src/example.c, exercises/anagram/test/test_anagram.c, exercises/bob/src/example.c, exercises/bob/src/example.h, exercises/bob/test/test_bob.c, exercises/gigasecond/src/example.c, exercises/gigasecond/src/example.h, exercises/gigasecond/test/test_gigasecond.c, exercises/grains/src/example.c, exercises/grains/test/test_grains.c, exercises/hamming/src/example.c, exercises/hamming/src/example.h, exercises/hamming/test/test_hamming.c, exercises/hello-world/src/example.c, exercises/hello-world/src/hello_world.c, exercises/hello-world/src/hello_world.h, exercises/hello-world/test/test_hello_world.c, exercises/leap/src/example.c, exercises/leap/src/example.h, exercises/leap/test/test_leap.c, exercises/pangram/src/example.c, exercises/pangram/test/test_pangram.c, exercises/raindrops/src/example.c, exercises/raindrops/src/example.h, exercises/raindrops/test/test_raindrops.c, indent.sh
=> Document coding style, add indent script, and Travis indent check, and apply coding style

exercises/anagram/makefile, exercises/bob/makefile, exercises/gigasecond/makefile, exercises/grains/makefile, exercises/hamming/makefile, exercises/hello-world/makefile, exercises/leap/makefile, exercises/pangram/makefile, exercises/raindrops/makefile
=> Make: rebuild when header files change

exercises/anagram/makefile, exercises/bob/makefile, exercises/bob/src/example.c, exercises/gigasecond/makefile, exercises/grains/makefile, exercises/hamming/makefile, exercises/hello-world/makefile, exercises/leap/makefile, exercises/leap/src/example.c, exercises/nth-prime/makefile, exercises/nth-prime/src/example.c, exercises/pangram/makefile, exercises/raindrops/makefile
Adding the new makefile to every test (and fixing warnings from bob and leap).
I was going to touch each one individually, but it turned out there were only 2 very minor fixes needed to conform.
Closes #61
=> Updating makefiles with new default flags.

config.json, exercises/beer-song/makefile, exercises/beer-song/src/example.c, exercises/beer-song/src/example.h, exercises/beer-song/test/test_beer_song.c, exercises/beer-song/test/vendor/unity.c, exercises/beer-song/test/vendor/unity.h, exercises/beer-song/test/vendor/unity_internals.h
=> Add beer-song exercise

config.json, exercises/difference-of-squares/makefile, exercises/difference-of-squares/src/example.c, exercises/difference-of-squares/src/example.h, exercises/difference-of-squares/test/test_difference_of_squares.c, exercises/difference-of-squares/test/vendor/unity.c, exercises/difference-of-squares/test/vendor/unity.h, exercises/difference-of-squares/test/vendor/unity_internals.h
Adds the 'difference-of-squares' exercise
=> Add difference-of-squares exercise

config.json, exercises/sum-of-multiples/makefile, exercises/sum-of-multiples/src/example.c, exercises/sum-of-multiples/src/example.h, exercises/sum-of-multiples/test/test_sum_of_multiples.c, exercises/sum-of-multiples/test/vendor/unity.c, exercises/sum-of-multiples/test/vendor/unity.h, exercises/sum-of-multiples/test/vendor/unity_internals.h
Adds 'sum-of-multiples' exercise
=> Add sum-of-multiples exercise

config.json, exercises/binary-search/makefile, exercises/binary-search/src/example.c, exercises/binary-search/src/example.h, exercises/binary-search/test/test_binary_search.c, exercises/binary-search/test/vendor/unity.c, exercises/binary-search/test/vendor/unity.h, exercises/binary-search/test/vendor/unity_internals.h
The only weird thing with this problem is returning an 'error flag' in the case where the value isn't found. I use the length of the array but that's not necessarily the best option, so I'm definitely open to suggestions.
=> binary-search: Adding bsearch problem.

config.json, exercises/roman-numerals/makefile, exercises/roman-numerals/src/example.c, exercises/roman-numerals/src/example.h, exercises/roman-numerals/test/test_roman_numerals.c, exercises/roman-numerals/test/vendor/unity.c, exercises/roman-numerals/test/vendor/unity.h, exercises/roman-numerals/test/vendor/unity_internals.h
See https://github.com/exercism/x-common/tree/master/exercises/roman-numerals
=> Add 'roman-numerals' exercise

config.json
=> Fix config.json so that "Hello World" is first exercise

.gitignore, config.json, exercises/clock/makefile, exercises/clock/src/clock.h, exercises/clock/src/example.c, exercises/clock/test/test_clock.c, exercises/clock/test/vendor/unity.c, exercises/clock/test/vendor/unity.h, exercises/clock/test/vendor/unity_internals.h
Added.Ds_Store to gitignore
Implemented the clock exercise.
Note the introduction of X Macro's to generate some of the test routines.  Only as an introduction.  It may be too complicated for a user to modify but I think it is a small enough introduction for users to appreciate the elimination of the duplication.  For these endless test cases -- it could have been applied more.
=> Clock Exercise

config.json, exercises/sieve/makefile, exercises/sieve/src/example.c, exercises/sieve/src/sieve.h, exercises/sieve/test/test_sieve.c, exercises/sieve/test/vendor/unity.c, exercises/sieve/test/vendor/unity.h, exercises/sieve/test/vendor/unity_internals.h
still providing sieve.h since I am allocating the results array.  Otherwise it is pretty straight forward
=> sieve exercise

exercises/allergies/src/allergies.h, exercises/allergies/src/example.h, exercises/anagram/src/anagram.h, exercises/atbash-cipher/src/example.h, exercises/beer-song/src/example.h, exercises/binary-search/src/example.h, exercises/bob/src/example.h, exercises/clock/src/clock.h, exercises/difference-of-squares/src/example.h, exercises/gigasecond/src/example.h, exercises/grains/src/example.h, exercises/hamming/src/example.h, exercises/hello-world/src/hello_world.h, exercises/largest-series-product/src/example.h, exercises/leap/src/example.h, exercises/meetup/src/example.h, exercises/nth-prime/src/example.h, exercises/pangram/src/example.h, exercises/phone-number/src/example.h, exercises/raindrops/src/example.h, exercises/rna-transcription/src/example.h, exercises/robot-simulator/src/robot_simulator.h, exercises/roman-numerals/src/example.h, exercises/series/src/series.h, exercises/sieve/src/sieve.h, exercises/sum-of-multiples/src/example.h, exercises/word-count/src/word_count.h
=> Use legal include guard names

docs/ABOUT.md, docs/INSTALLATION.md, docs/LEARNING.md, docs/RESOURCES.md
This is heavily influenced by the documentation at `xcpp` so it's probably missing some good resources, but it's far better than the mostly nothing that we have now.
Closes #100
=> Added full track documentation

README.md
=> Add no tabs specification to text and shell command

config.json, exercises/triangle/makefile, exercises/triangle/src/example.c, exercises/triangle/src/example.h, exercises/triangle/src/triangle.h, exercises/triangle/test/test_triangle.c, exercises/triangle/test/vendor/unity.c, exercises/triangle/test/vendor/unity.h, exercises/triangle/test/vendor/unity_internals.h
i don't know if this satisfies the [https://github.com/exercism/x-common/blob/master/exercises/triangle/canonical-data.json](canonical-data.json)
=> triangle exercise added

exercises/rna-transcription/test/test_rna_transcription.c
Also adjust strlen argument as mentioned by @patricksjackson, also in issue #116
=> Prevent segfault early on in TDD cycle per issue #116

config.json, exercises/react/makefile, exercises/react/src/example.c, exercises/react/src/react.h, exercises/react/test/test_react.c, exercises/react/test/vendor/unity.c, exercises/react/test/vendor/unity.h, exercises/react/test/vendor/unity_internals.h
~~This is a work in progress:~~
1. ~~Not all tests have been added yet.~~
2. ~~The example does not yet have remove_callback. Should be easy enough to add, given everything else is reasonable~~.
At this point, it would be a good time to review the API being presented to the student in react.h to see if it is reasonable. ~~There are a few questions marked TODO that deserve attention as well~~.
If at any point you feel the answer should be "This exercise should not be added to this track", don't hesitate to say that as well.
=> react: Add to track

config.json, exercises/nucleotide-count/makefile, exercises/nucleotide-count/src/example.c, exercises/nucleotide-count/src/example.h, exercises/nucleotide-count/test/test_nucleotide_count.c, exercises/nucleotide-count/test/vendor/unity.c, exercises/nucleotide-count/test/vendor/unity.h, exercises/nucleotide-count/test/vendor/unity_internals.h
Closed the work in progress pull request and created this one after finishing the basic implementation.
=> Nucleotide Count - Exercise Added

.travis.yml, bin/run-tests, exercises/atbash-cipher/src/example.c, exercises/phone-number/src/example.c, exercises/rna-transcription/src/example.c, exercises/roman-numerals/src/example.c, exercises/sieve/src/example.c
Opening this to test against Travis. I expect that this will need to patch a lot of the existing solutions to get it to pass.
Closes #127
**Edit:** Apparently only 5 problems needed patching, and all of them were in the example solutions, so these patches don't change any of the user interface.
=> Adding Valgrind check to Travis CI

exercises/phone-number/src/example.c, exercises/phone-number/test/test_phone_number.c
=> Phone-number: Add missing tests and adjust example to suit changes

config.json, exercises/pascals-triangle/makefile, exercises/pascals-triangle/src/example.c, exercises/pascals-triangle/src/example.h, exercises/pascals-triangle/test/test_pascals_triangle.c, exercises/pascals-triangle/test/vendor/unity.c, exercises/pascals-triangle/test/vendor/unity.h, exercises/pascals-triangle/test/vendor/unity_internals.h
=> Adding the new pascals triangle

config.json, exercises/perfect-numbers/makefile, exercises/perfect-numbers/src/example.c, exercises/perfect-numbers/src/example.h, exercises/perfect-numbers/src/perfect_numbers.h, exercises/perfect-numbers/test/test_perfect_numbers.c, exercises/perfect-numbers/test/vendor/unity.c, exercises/perfect-numbers/test/vendor/unity.h, exercises/perfect-numbers/test/vendor/unity_internals.h
Every test is from [canonical-data.json](https://github.com/exercism/x-common/blob/master/exercises/perfect-numbers/canonical-data.json) , and as mentioned in canonical-data.json ,  0 is not a natural number , is that correct , because as i recall , Natural Numbers are set of positive and non-negative numbers ? .. which we can say 0 is a natural number? ..
=> Adding Perfect Number exercise

config.json, exercises/palindrome/makefile, exercises/palindrome/src/example.c, exercises/palindrome/src/example.h, exercises/palindrome/test/test_palindrome.c, exercises/palindrome/test/vendor/unity.c, exercises/palindrome/test/vendor/unity.h, exercises/palindrome/test/vendor/unity_internals.h
[description](https://github.com/exercism/x-common/blob/master/exercises/palindrome-products/description.md).
I did a first implementation of the Palindrome Product exercise, but there is surely some things that can be improved.
=> Palindrome Product exercise added

config.json, exercises/acronym/makefile, exercises/acronym/src/example.c, exercises/acronym/src/example.h, exercises/acronym/test/test_acronym.c, exercises/acronym/test/vendor/unity.c, exercises/acronym/test/vendor/unity.h, exercises/acronym/test/vendor/unity_internals.h
Added example.c/.h and test source, added item to config JSON.
Can't recall if I need to do anything further to add an exercise?
=> Add acronym exercise

config.json, exercises/isogram/makefile, exercises/isogram/src/example.c, exercises/isogram/src/example.h, exercises/isogram/test/test_isogram.c, exercises/isogram/test/vendor/unity.c, exercises/isogram/test/vendor/unity.h, exercises/isogram/test/vendor/unity_internals.h
Added tests, example.c/.h and added info to config.json
=> Add isogram exercise

docs/SNIPPET.txt
Unsure if the snippet is intended to be the easiest or the simplest. 
This is probably better for the latter option though as it reduces the code by 4 lines, one of which includes an entirely unused library.
=> simplify snippet

README.md, indent.sh
=> Detect and use gindent if available

exercises/all-your-base/test/test_all_your_base.c
Change helper function from uint16_t to int16_t.
Fix negative data test case
Closes #175
=> Update unit tests all-your-base

config.json
Moved Anagram later in the track, closing #180
=> Moved exercise Anagram to later in track closing issue #180

exercises/hello-world/src/example.c, exercises/hello-world/src/hello_world.c, exercises/hello-world/src/hello_world.h, exercises/hello-world/test/test_hello_world.c
=> Simplify Hello World and sync it with canonical JSON

indent.sh
I think this would help new developers I missed the notes about the indent in the README.md
=> Added message output to indent.sh

exercises/all-your-base/src/example.c, exercises/all-your-base/src/example.h
Updated all names as discussed in issue #184
=> Update all-your-base exercise to snake case per #184

exercises/allergies/src/allergies.h, exercises/allergies/src/example.c, exercises/allergies/src/example.h, exercises/allergies/test/test_allergies.c
Updates snake case to all lower case per #184
=> Update snake case for allergies exercise

exercises/isogram/src/example.c, exercises/isogram/src/example.h, exercises/isogram/test/test_isogram.c
Update isogram exercise to snake case per #184
=> Update isogram exercise to use snake case

exercises/anagram/src/anagram.h, exercises/anagram/src/example.c, exercises/anagram/test/test_anagram.c
Update anagram exercise to snake case per #184
=> Update anagram exercise to snake case

exercises/meetup/src/example.c, exercises/meetup/src/example.h, exercises/meetup/test/test_meetup.c
Update meetup exercise to snake case per #184
=> Update meetup exercise to snake case

config.json, exercises/acronym/README.md, exercises/all-your-base/README.md, exercises/allergies/README.md, exercises/atbash-cipher/README.md, exercises/beer-song/README.md, exercises/binary/README.md, exercises/grains/README.md, exercises/isogram/README.md, exercises/leap/README.md, exercises/meetup/README.md, exercises/nucleotide-count/README.md, exercises/palindrome-products/README.md, exercises/pangram/README.md, exercises/pascals-triangle/README.md, exercises/perfect-numbers/README.md, exercises/phone-number/README.md, exercises/roman-numerals/README.md, exercises/scrabble-score/README.md, exercises/space-age/README.md, exercises/triangle/README.md, exercises/word-count/README.md
These are updates run with the configlet tool using the latest version of the problem-specifications repo.
I used it to reformat the config.json and to regenerate the README's for the exercises. Once installing configlet (and pulling the latest problem-specifications HEAD into the path "..\problem-specifications", relative to the C track repo), it's just these commands from the C track root:
```
configlet fmt .
configlet generate .
```
=> Configlet updates

exercises/nucleotide-count/src/example.c
Update nucleotide count exercise to snake case per #184
=> Update nucleotide count exercise to snake case

exercises/palindrome-products/src/example.c, exercises/palindrome-products/src/example.h, exercises/palindrome-products/test/test_palindrome_products.c
Update palindrome product exercise to snake case per #184
Also took the chance to make the type names more relevant to its actual contents and to add new lines between the test cases and the `UnityBegin()` & `UnityEnd()` calls as per other exercises
=> Update palindrome products exercise to snake case

exercises/clock/test/test_clock.c, exercises/meetup/test/test_meetup.c, exercises/series/src/example.c, exercises/series/src/series.h, exercises/series/test/test_series.c
Closes #187, #167, also fixes snake case in series #184
=> Removed Xmacros from series, meetup, clock

exercises/space-age/src/example.c, exercises/space-age/src/example.h, exercises/space-age/test/test_space_age.c
Update space age exercise to snake case per #184
=> Update space age exercise to snake case

exercises/triangle/src/example.c, exercises/triangle/src/example.h, exercises/triangle/src/triangle.h, exercises/triangle/test/test_triangle.c
Update triangle exercise to snake case per #184
=> Update triangle exercise to snake case

exercises/sieve/src/example.c, exercises/sieve/src/sieve.h, exercises/sieve/test/test_sieve.c
Update sieve exercise to snake case per #184
=> Update sieve exercise to snake case

exercises/word-count/src/example.c, exercises/word-count/src/word_count.h, exercises/word-count/test/test_word_count.c
Update word count exercise to snake case per #184
=> Update word count exercise to snake case

exercises/allergies/src/allergies.h, exercises/allergies/src/example.c, exercises/allergies/src/example.h, exercises/allergies/test/test_allergies.c
=> Make enums uppercase for Allergen

exercises/sum-of-multiples/src/example.c, exercises/sum-of-multiples/test/test_sum_of_multiples.c
closes #188  surprisingly I did not have to update the solution.  Is this worth merging?
=> Additional test cases for Sum of Multiples

exercises/hello-world/src/example.c
Includes left from previous implementation
=> Remove unneeded includes

docs/SNIPPET.txt
hello-world exercise changed with #178 to match canonical json
=> Update snippet to follow hello-world exercise

README.md
The Linux folk moved their docs.
=> Update dead link to Linux kernal docs

exercises/space-age/src/example.h, exercises/space-age/test/test_space_age.c
Update space age exercise enum case per #184
=> Update space age exercise enum case

exercises/perfect-numbers/src/example.c, exercises/perfect-numbers/src/example.h, exercises/perfect-numbers/src/perfect_numbers.h, exercises/perfect-numbers/test/test_perfect_numbers.c
Update perfect number exercise enum case per #184
=> Update perfect number exercise enum case

exercises/react/src/example.c
Update react exercise enum case per #184
=> Update react exercise enum case

exercises/robot-simulator/src/example.c, exercises/robot-simulator/src/robot_simulator.h, exercises/robot-simulator/test/test_robot_simulator.c
Update robot simulator enum case per #184
=> Update robot simulator enum case

exercises/allergies/test/test_allergies.c
TEST_IGNORE was applied to all tests and one helper function, so the first time `make test` was run it ran 0 tests.
=> Fix TEST_IGNORE on allergies

exercises/raindrops/src/example.c, exercises/raindrops/src/example.h, exercises/raindrops/test/test_raindrops.c
When attempting to solve the raindrops exercise in C, I found the method signature unnecessarily complex, and hard to understand.
Therefore I have here changed it to an implementation I personally believe to be easier to understand and solve the same problem.
=> Simplified the implementation of the raindrops exercise and its tests.

README.md
Adds some "front page" information for any potential contributors interested in hacktoberfest
=> Add hacktoberfest information to readme

config.json, exercises/collatz-conjecture/README.md, exercises/collatz-conjecture/makefile, exercises/collatz-conjecture/src/collatz_conjecture.h, exercises/collatz-conjecture/src/example.c, exercises/collatz-conjecture/test/test_collatz_conjecture.c, exercises/collatz-conjecture/test/vendor/unity.c, exercises/collatz-conjecture/test/vendor/unity.h, exercises/collatz-conjecture/test/vendor/unity_internals.h
Okay, so it's been a year and I need help with `config.json`.  What's this `uuid`?
=> Add Collatz Conjecture exercise

docs/C_STYLE_GUIDE.md
Initial attempt at the style guide.
Am still unsure on if the capitalization for constants applies only to globals or not.
I intend to add further commits with a short description of the formatting as set by the parameters we pass to `indent` (line length, brace placement, etc)
=> Create C style guide

config.json, exercises/queen-attack/README.md, exercises/queen-attack/makefile, exercises/queen-attack/src/example.c, exercises/queen-attack/src/queen_attack.h, exercises/queen-attack/test/test_queen_attack.c, exercises/queen-attack/test/vendor/unity.c, exercises/queen-attack/test/vendor/unity.h, exercises/queen-attack/test/vendor/unity_internals.h
Problem specification: https://github.com/exercism/problem-specifications/tree/master/exercises/queen-attack
=> Add queen-attack exercise

docs/C_STYLE_GUIDE.md
Clarify usage of `TEST_IGNORE()` for future contributions. This is according to the discussion during PR #179
=> Add style information for TEST_IGNORE()

docs/CONTRIBUTING.md
This  hopefully fleshes out the CONTRIBUTING.md document a little more, especially with regard to the point of view of someone for who this may be their first exposure to contributing to exercism, open source in general or even use of git.
=> Improve contributing document

exercises/word-count/src/example.c, exercises/word-count/src/word_count.h, exercises/word-count/test/test_word_count.c
Added tests to make sure that people don't overrun buffers, since this has two arrays it should be a good exercise for it.
Closes #207
=> Add buffer overrun tests to word_count

exercises/phone-number/test/test_phone_number.c
Another instance where a helper function had me confused on which one was the first test.  The helper function was so simple I just inlined.  Net increase in 4 LOC, but IMHO improved readability.
=> Inline helper function test_phone_number

docs/TESTS.md
Updates TESTS.md to remove and replace the empty sections marked with `??`, as per #230
=> Complete TESTS documentation file

README.md, config.json
=> Launch the C track

config.json, exercises/anagram/src/anagram.h, exercises/anagram/src/example.c, exercises/anagram/test/test_anagram.c
Took more changes than I thought to require no memory management out of anagram.  Closes #183
=> Modified anagram to not require any memory management

config.json
Fixes #226 
I'll update this once #223 and #224 get merged, but I gotta open this now so I can get my shirt!
=> Change UUIDs to "longer" version generated by configlet

config.json
See https://github.com/exercism/c/pull/227#discussion_r150229995
=> Unlock collatz-conjecture by pascals-triangle

exercises/hello-world/makefile
=> hello-world: Add memcheck make target

exercises/hello-world/src/hello_world.c
The includes are left from the old implementation and are not needed for the current one
=> hello-world: remove unneeded includes

exercises/all-your-base/src/example.c, exercises/beer-song/src/example.c, exercises/meetup/src/example.c, exercises/nucleotide-count/src/example.c, exercises/raindrops/src/example.c, exercises/sieve/src/example.c
While testing CppCheck static analysis I see small items that could be fixed in several exercises.
This PR fixes those. Each commit is in relation to items in a different exercise.
=> Fix small static analysis items

exercises/hamming/test/test_hamming.c
Two of the tests aren't being called at all.
=> Call missing tests for hamming exercise

exercises/series/test/test_series.c
It looks like there is a copy paste mistake.
=> Fix call to UnityBegin() in test_series.c

exercises/pangram/test/test_pangram.c
Solves #262 
Changed the tests to match the canonical data (https://github.com/exercism/problem-specifications/tree/master/exercises/pangram).
=> pangram: Update test cases to conform to canonical data

exercises/palindrome-products/src/example.c, exercises/palindrome-products/src/example.h, exercises/palindrome-products/test/test_palindrome_products.c
- check for the factors of the returned palindromes;
- more test cases.
=> Complete palindrome_products to fully match the problem description

config.json, exercises/pig-latin/README.md, exercises/pig-latin/makefile, exercises/pig-latin/src/example.c, exercises/pig-latin/src/example.h, exercises/pig-latin/test/test_pig_latin.c, exercises/pig-latin/test/vendor/unity.c, exercises/pig-latin/test/vendor/unity.h, exercises/pig-latin/test/vendor/unity_internals.h
Although the specification says nothing about it, I took the decision to just copy not just the spaces, but all non-words to the output; and also make everything lowercase.
Let me know what you guys think about this.
I am learning a lot around here, so don't judge me too hard if I forgot again something.
=> Implement exercise 'pig-latin'

exercises/secret-handshake/src/example.c, exercises/secret-handshake/src/example.h, exercises/secret-handshake/test/test_secret_handshake.c
- move the macro ARRAY_SIZE to be defined in both the testfile and the source file;
- thanks to @wolf99 for pointing this out.
=> 'secret-handshake' improvement:

docs/RESOURCES.md
=> Remove broken link to C book list

config.json
I've added auto_approve to the hello-world exercise for issue #303
=> Added auto_approve to hello-world exercise

exercises/minesweeper/src/example.c, exercises/minesweeper/src/example.h, exercises/minesweeper/test/test_minesweeper.c
Closes #297 
Thanks @redsled84 for pointing this out 👍
=> Add function for freeing minesweeper annotation

exercises/word-count/src/word_count.h
Closes #299
Thanks @h-3-0 for pointing this out 👍
=> Word Count: Add a byte for null terminator

exercises/binary-search-tree/README.md, exercises/bracket-push/README.md, exercises/crypto-square/README.md, exercises/diamond/README.md, exercises/etl/README.md, exercises/luhn/README.md, exercises/minesweeper/README.md, exercises/pig-latin/README.md, exercises/prime-factors/README.md, exercises/rna-transcription/README.md, exercises/run-length-encoding/README.md, exercises/say/README.md, exercises/secret-handshake/README.md, exercises/two-fer/README.md, exercises/wordy/README.md
This should cover the changes in #307 as well.
=> Run configlet generate to update READMEs

exercises/word-count/test/test_word_count.c
Closes #310
Thanks @mikewalker
=> Account for null terminator in strncpy

docs/TESTS.md
=> Update TESTS.md to show `mkdir src`

exercises/phone-number/src/example.c, exercises/phone-number/test/test_phone_number.c
@ryanplusplus hows this look as a first crack at https://github.com/exercism/c/issues/328?
=> phone-number: update test cases to match specifications

exercises/phone-number/src/example.h
Missed removing the function prototypes from header with last PR (https://github.com/exercism/c/pull/329) that we merged. :(
=> remove dead code from header

exercises/isogram/test/test_isogram.c
- Added test for NULL input
- Added test for duplicated letters on the ends of character arrays
- ~~Added test for terminating as soon as a duplicate is found~~
=> Extend C Isogram Test Suite

exercises/isogram/test/test_isogram.c, exercises/sieve/test/test_sieve.c
Fixes https://github.com/exercism/c/issues/337.
=> Correct unitybegin

docs/CONTRIBUTING.md
See https://github.com/exercism/exercism/issues/4441.
=> Update URL for Exercism Code of Conduct link.

exercises/linked-list/src/example.c
Should resolve error showing in clang build (#345)
=> linked-list: Initialize result in pop()

exercises/binary-search/test/test_binary_search.c
=> Removing pointer compare in binary-search.

exercises/palindrome-products/test/test_palindrome_products.c
=> palindrome-products: Made the check_factors test function order-insensitive

exercises/clock/src/clock.h, exercises/clock/src/example.c, exercises/clock/test/test_clock.c
Update the solution to v2.4.0 of exercise canonical data.
Also adjust arguments to struct per #374.
=> Update clock to v2.4.0

exercises/word-count/test/test_word_count.c
Fixes #397 
Thanks @lukebiggerstaff for finding the issue
=> Fix word length check in word-count

config.json, exercises/darts/README.md, exercises/darts/makefile, exercises/darts/src/darts.c, exercises/darts/src/darts.h, exercises/darts/src/example.c, exercises/darts/src/example.h, exercises/darts/test/test_darts.c, exercises/darts/test/vendor/unity.c, exercises/darts/test/vendor/unity.h, exercises/darts/test/vendor/unity_internals.h
Towards #390 
Unsure of best place for these exercises in `config.json` - maybe that can be decided on #390?
=> darts: add exercise

config.json, exercises/resistor-color-duo/README.md, exercises/resistor-color-duo/makefile, exercises/resistor-color-duo/src/example.c, exercises/resistor-color-duo/src/example.h, exercises/resistor-color-duo/src/resistor_color_duo.c, exercises/resistor-color-duo/src/resistor_color_duo.h, exercises/resistor-color-duo/test/test_resistor_color_duo.c, exercises/resistor-color-duo/test/vendor/unity.c, exercises/resistor-color-duo/test/vendor/unity.h, exercises/resistor-color-duo/test/vendor/unity_internals.h
=> resistor-color-duo: add exercise

config.json, exercises/resistor-color-trio/README.md, exercises/resistor-color-trio/makefile, exercises/resistor-color-trio/src/example.c, exercises/resistor-color-trio/src/example.h, exercises/resistor-color-trio/src/resistor_color_trio.c, exercises/resistor-color-trio/src/resistor_color_trio.h, exercises/resistor-color-trio/test/test_resistor_color_trio.c, exercises/resistor-color-trio/test/vendor/unity.c, exercises/resistor-color-trio/test/vendor/unity.h, exercises/resistor-color-trio/test/vendor/unity_internals.h
=> resistor-color-trio: add exercise

exercises/square-root/test/test_square_root.c
=> Fix test name in square-root

exercises/saddle-points/src/example.c, exercises/saddle-points/src/example.h, exercises/saddle-points/test/test_saddle_points.c
fix https://github.com/exercism/c/issues/413
=> add free() to points and rename function

config.json, exercises/pythagorean-triplet/README.md, exercises/pythagorean-triplet/makefile, exercises/pythagorean-triplet/src/example.c, exercises/pythagorean-triplet/src/example.h, exercises/pythagorean-triplet/src/pythagorean_triplet.c, exercises/pythagorean-triplet/src/pythagorean_triplet.h, exercises/pythagorean-triplet/test/test_pythagorean_triplet.c, exercises/pythagorean-triplet/test/vendor/unity.c, exercises/pythagorean-triplet/test/vendor/unity.h, exercises/pythagorean-triplet/test/vendor/unity_internals.h
=> pythagorean triplet: add exercise

config.json, exercises/rational-numbers/README.md, exercises/rational-numbers/makefile, exercises/rational-numbers/src/example.c, exercises/rational-numbers/src/example.h, exercises/rational-numbers/src/rational_numbers.c, exercises/rational-numbers/src/rational_numbers.h, exercises/rational-numbers/test/test_rational_numbers.c, exercises/rational-numbers/test/vendor/unity.c, exercises/rational-numbers/test/vendor/unity.h, exercises/rational-numbers/test/vendor/unity_internals.h
=> rational-numbers: add exercise

exercises/crypto-square/test/test_crypto_square.c
Fixes the issue discovered in #420 
(😱 issues with 420! 🚬 😏 )
=> crypto-square: fix argument to UnityBegin()

exercises/list-ops/test/test_list_ops.c
=> list-ops: Fix test_append_empty_lists

config.json, exercises/circular-buffer/README.md, exercises/circular-buffer/makefile, exercises/circular-buffer/src/circular_buffer.c, exercises/circular-buffer/src/circular_buffer.h, exercises/circular-buffer/src/example.c, exercises/circular-buffer/src/example.h, exercises/circular-buffer/test/test_circular_buffer.c, exercises/circular-buffer/test/vendor/unity.c, exercises/circular-buffer/test/vendor/unity.h, exercises/circular-buffer/test/vendor/unity_internals.h
=> circular-buffer: add exercise

config.json, exercises/grade-school/README.md, exercises/grade-school/makefile, exercises/grade-school/src/example.c, exercises/grade-school/src/example.h, exercises/grade-school/src/grade_school.c, exercises/grade-school/src/grade_school.h, exercises/grade-school/test/test_grade_school.c, exercises/grade-school/test/vendor/unity.c, exercises/grade-school/test/vendor/unity.h, exercises/grade-school/test/vendor/unity_internals.h
Really not sure where in the track to add this 🤷‍♂ particularly now v3 is started.
(This is why lint is failing in the CI, I haven't added the exercise to the config.json)
Suggestions welcome.
For #390
=> WIP: grade-school: add exercise

docs/TESTS.md
=> Add make clean note

exercises/hello-world/src/hello_world.c
=> Fix typo in comment in hello_world.c

exercises/resistor-color/src/resistor_color.h, exercises/resistor-color/test/test_resistor_color.c
This will fix what caused some pain [here](https://exercism.io/mentor/solutions/d7b4724fa9a74b7f996001a3a51cf626)
=> Added a static assert

docs/INSTALLATION.md, docs/TESTS.md
=> removed mentions of VS

exercises/armstrong-numbers/src/armstrong_numbers.h, exercises/armstrong-numbers/src/example.c, exercises/armstrong-numbers/src/example.h
I hate returning int instead of bool.
=> Use stdbool for armstrongnumbers

exercises/anagram/src/anagram.h, exercises/anagram/src/example.c, exercises/anagram/test/test_anagram.c
These are «candidate words» not «candidate candidates».
=> Clarify the structure of a candidate in anagram exercise.

exercises/anagram/src/anagram.h, exercises/anagram/test/test_anagram.c
See https://github.com/exercism/c/pull/458
=> Ensure that empty anagram solution does not double-free

.travis.yml, config.json, exercises/anagram/README.md, exercises/bob/README.md, exercises/difference-of-squares/README.md, exercises/etl/README.md, exercises/gigasecond/README.md, exercises/grade-school/README.md, exercises/grains/README.md, exercises/leap/README.md, exercises/linked-list/src/example.c, exercises/list-ops/README.md, exercises/luhn/README.md, exercises/minesweeper/README.md, exercises/palindrome-products/README.md, exercises/rail-fence-cipher/README.md, exercises/raindrops/README.md, exercises/resistor-color/README.md, exercises/scrabble-score/README.md, exercises/space-age/README.md, exercises/two-fer/README.md, exercises/word-count/README.md, exercises/wordy/README.md
This normalizes our `config.json` (in this case it just put the concepts in alphabetical order), updates the readmes, and (hopefully) fixes indent issues that result from the change in behavior for `indent` by updating to Ubuntu 18.04 in our CI build.
=> Ran configlet fmt, ran configlet generate, ran indent.sh, and updated travis.yaml

exercises/all-your-base/.meta/tests.toml, exercises/all-your-base/src/example.c, exercises/all-your-base/test/test_all_your_base.c
- Add missing test cases
- Update implementation to handle leading zeros for one of these new cases
- Adjust existing case naming to match spec
- Refactor helper function to indicate it is a check rather than a test (in line with practice in other exercises)
=> all-your-base: update to most recent spec

exercises/acronym/.meta/tests.toml, exercises/acronym/src/example.c, exercises/acronym/test/test_acronym.c
- Add missing test cases
- Update implementation to handle leading underscores for one of these new cases
- Move C-specific extra test cases (null and empty string) to top
- Remove outdated test cases
- Refactor helper function to indicate it is a check rather than a test (in line with practice in other exercises)
=> acronym: Update to most recent spec

exercises/allergies/test/test_allergies.c
- Add missing test cases
- Update names of existing test cases
=> allergies: Update to most recent spec

config.json, exercises/rational-numbers/README.md, exercises/two-bucket/.meta/tests.toml, exercises/two-bucket/README.md, exercises/two-bucket/makefile, exercises/two-bucket/src/example.c, exercises/two-bucket/src/example.h, exercises/two-bucket/src/two_bucket.c, exercises/two-bucket/src/two_bucket.h, exercises/two-bucket/test/test_two_bucket.c, exercises/two-bucket/test/vendor/unity.c, exercises/two-bucket/test/vendor/unity.h, exercises/two-bucket/test/vendor/unity_internals.h
See https://github.com/exercism/problem-specifications/tree/master/exercises/two-bucket
=> Add two-bucket exercise

exercises/atbash-cipher/.meta/tests.toml, exercises/atbash-cipher/test/test_atbash_cipher.c
=> atbash-cipher: align with specification per #496

exercises/binary/.meta/tests.toml, exercises/binary/test/test_binary.c
=> binary: align with specification per #498

exercises/bob/.meta/tests.toml, exercises/bob/test/test_bob.c
=> bob: align with specification per #500

exercises/difference-of-squares/.meta/tests.toml, exercises/difference-of-squares/test/test_difference_of_squares.c
=> difference-of-squares: align with specification per #502

exercises/binary-search/.meta/tests.toml, exercises/binary-search/test/test_binary_search.c
=> binary-search: align with specification per #499

exercises/leap/.meta/tests.toml, exercises/leap/src/example.c, exercises/leap/src/example.h, exercises/leap/src/leap.h, exercises/leap/test/test_leap.c
=> leap: align with specification per #508

exercises/list-ops/.meta/tests.toml, exercises/list-ops/src/example.c, exercises/list-ops/src/example.h, exercises/list-ops/src/list_ops.h, exercises/list-ops/test/test_list_ops.c
=> List ops update

exercises/luhn/.meta/tests.toml, exercises/luhn/test/test_luhn.c
=> luhn: align with specification per #510

exercises/matching-brackets/.meta/tests.toml, exercises/matching-brackets/test/test_matching_brackets.c
=> matching-brackets: align with specification per #511

exercises/meetup/.meta/tests.toml, exercises/meetup/test/test_meetup.c
=> meetup: align with specification per #512

exercises/nth-prime/.meta/tests.toml, exercises/nth-prime/test/test_nth_prime.c
=> nth-prime: align with specification per #513

exercises/queen-attack/.meta/tests.toml, exercises/queen-attack/test/test_queen_attack.c
=> queen-attack: align with specification per #518

exercises/pascals-triangle/.meta/tests.toml, exercises/pascals-triangle/src/example.c, exercises/pascals-triangle/src/example.h, exercises/pascals-triangle/src/pascals_triangle.h, exercises/pascals-triangle/test/test_pascals_triangle.c
=> pascals-triangle: align with specification per #516

exercises/hello-world/.meta/tests.toml, exercises/hello-world/test/test_hello_world.c
=> hello-world: align with specification per #505

exercises/raindrops/.meta/tests.toml, exercises/raindrops/test/test_raindrops.c
=> raindrops: align with specification per #520

exercises/react/.meta/tests.toml, exercises/react/src/react.h, exercises/react/test/test_react.c
=> react: align with specification per #521

exercises/rna-transcription/.meta/tests.toml, exercises/rna-transcription/test/test_rna_transcription.c
=> rna-transcription: align with specification per #522

exercises/robot-simulator/.meta/tests.toml, exercises/robot-simulator/src/example.c, exercises/robot-simulator/src/robot_simulator.h, exercises/robot-simulator/test/test_robot_simulator.c
=> Robot simulator update

exercises/series/.meta/tests.toml, exercises/series/src/example.c, exercises/series/src/series.h, exercises/series/test/test_series.c
=> series: align with specification per #525

exercises/word-count/.meta/tests.toml, exercises/word-count/src/example.c, exercises/word-count/src/word_count.h, exercises/word-count/test/test_word_count.c
=> word-count: align with specification per #529

exercises/triangle/.meta/tests.toml, exercises/triangle/src/example.c, exercises/triangle/src/example.h, exercises/triangle/test/test_triangle.c
=> triangle: align with specification per #528

exercises/space-age/.meta/tests.toml, exercises/space-age/src/example.c, exercises/space-age/src/example.h, exercises/space-age/src/space_age.h, exercises/space-age/test/test_space_age.c
=> space-age: align with specification per #526

exercises/sum-of-multiples/.meta/tests.toml, exercises/sum-of-multiples/src/example.c, exercises/sum-of-multiples/src/example.h, exercises/sum-of-multiples/src/sum_of_multiples.h, exercises/sum-of-multiples/test/test_sum_of_multiples.c
=> sum-of-multiples: align with specification per #527

.github/workflows/format-code.yml
This should make the workflow commit trigger the CI
=> Use deploy key

bin/check-unitybegin
Forgot to update the searched string on #618
=> Fix check-unitybegin script

exercises/practice/prime-factors/.meta/tests.toml, exercises/practice/prime-factors/test_prime_factors.c
New tests have been recently added to the spec.
This commit updates the tests to match.
=> prime-factors: update to new spec

.github/workflows/build.yml, .github/workflows/checks.yml
=> Split checks from build, add clang

.github/workflows/build.yml, .github/workflows/checks.yml
=> Correct workflow names

docs/INSTALLATION.md, docs/LEARNING.md, docs/TESTS.md
Noticed some problems in the docs. This PR fixes them
=> Installation doc fixes

exercises/practice/hamming/.meta/tests.toml
Per updated canonical-data problem spec
=> hamming: update tests.toml

exercises/practice/isogram/.meta/tests.toml, exercises/practice/isogram/test_isogram.c
Per updated canonical-data problem spec
=> isogram: Add new test

exercises/practice/luhn/.meta/tests.toml, exercises/practice/luhn/test_luhn.c
Per updated canonical-data problem spec
=> luhn: Add new test

exercises/practice/anagram/.meta/tests.toml, exercises/practice/anagram/test_anagram.c
Per updated canonical-data problem spec
=> anagram: Add new test

exercises/practice/linked-list/.meta/tests.toml
Got missed in #633
@ErikSchierboom this may need doing for all other tracks that implement linked-list also. The problem may also have occurred for other exercises that C track does not implement.
=> linked-list: update tests.toml to new spec

docs/CONTRIBUTING.md
Would like to have some kind of link from here to @bergjohan 's work.
Not sure what else to say about it - any suggestions?
=> Mention test runner

exercises/practice/acronym/.meta/config.json, exercises/practice/anagram/.meta/config.json, exercises/practice/clock/.meta/config.json, exercises/practice/collatz-conjecture/.meta/config.json, exercises/practice/complex-numbers/.meta/config.json, exercises/practice/hello-world/.meta/config.json, exercises/practice/isogram/.meta/config.json, exercises/practice/pangram/.meta/config.json, exercises/practice/queen-attack/.meta/config.json, exercises/practice/rail-fence-cipher/.meta/config.json, exercises/practice/react/.meta/config.json, exercises/practice/robot-simulator/.meta/config.json, exercises/practice/series/.meta/config.json, exercises/practice/sieve/.meta/config.json, exercises/practice/sublist/.meta/config.json, exercises/practice/word-count/.meta/config.json
=> Remove example.h from configs where file doesnt exist

exercises/practice/grade-school/.meta/example.c, exercises/practice/grade-school/.meta/example.h, exercises/practice/grade-school/grade_school.h, exercises/practice/grade-school/test_grade_school.c
=> Stricter tests for grade-school

exercises/practice/all-your-base/test_all_your_base.c
=> all-your-base: fix stringop-overflow issue

exercises/practice/anagram/test_anagram.c
=> anagram: remove non-ASCII test cases

exercises/practice/beer-song/.meta/example.c, exercises/practice/beer-song/.meta/example.h, exercises/practice/beer-song/.meta/tests.toml, exercises/practice/beer-song/beer_song.h, exercises/practice/beer-song/test_beer_song.c
=> beer-song: update to latest spec

exercises/practice/phone-number/test_phone_number.c
=> Fix duplicate test in phone-number

exercises/practice/linked-list/test_linked_list.c
=> c-track issue #689 - to allow mentors to override TEST_IGNORE()

exercises/practice/pascals-triangle/test_pascals_triangle.c, exercises/practice/robot-simulator/test_robot_simulator.c, exercises/practice/sieve/test_sieve.c
I doubled checked and found only those 3.
=> Fix remaining #689 exercises (hopefully nothing forgotten)

exercises/practice/all-your-base/.meta/example.c, exercises/practice/all-your-base/test_all_your_base.c
I have changed two tests: test_single_zero, test_multiple_zeros.
They have expected 0 length result array but as input and output bases are correct these are just proper representations of zero number.
So the results should be zeros, which in both cases are arrays of length 1 with zero digit.
=> All your base tests fix

docs/CONTRIBUTING.md, reference/README.md, reference/implementing-a-concept-exercise.md
Noticed some small issues reported by markdown linter
=> Fix some small markdown issues

docs/C_STYLE_GUIDE.md
=> Fix minor typo

.github/workflows/checks.yml, .github/workflows/test.yml, bin/check-include-guards, bin/check-unitybegin, bin/run-tests, bin/verify-unity-version
I realised during #735  that tooling and CI does not yet cover concept exercises.
This PR should resolve that.
=> CI for concepts

docs/CONTRIBUTING.md
Fixes broken links identified in https://github.com/exercism/c/pull/774
=> Fix broken links identified by Lychee

exercises/practice/diamond/.meta/example.c
Follow-up to https://github.com/exercism/c/pull/780
=> Formatted changes to diamond example

concepts/bits/introduction.md
=> bit concept: update introduction.md

exercises/practice/complex-numbers/.meta/tests.toml, exercises/practice/complex-numbers/test_complex_numbers.c
Adds new test `test_exponential_resulting_in_number_with_real_and_imaginary_part()`, per the updated problem spec
=> complex-numbers: update test

exercises/practice/series/.meta/tests.toml, exercises/practice/series/test_series.c
Add new test per the updated problem spec.
=> series: update tests

exercises/practice/say/.meta/tests.toml, exercises/practice/say/test_say.c
Adds new tests per the updated problem spec.
=> say: update tests

exercises/practice/triangle/.meta/tests.toml, exercises/practice/triangle/test_triangle.c
New tests added, and existing one updated per the updated problem spec.
=> triangle: update tests

exercises/practice/word-count/.docs/instructions.md, exercises/practice/word-count/.meta/tests.toml, exercises/practice/word-count/test_word_count.c
Adds new test and updates instructions doc per the updated problem spec.
=> word-count: update tests and docs

exercises/practice/leap/.docs/instructions.md
Updates introduction doc per the updated problem spec.
I think this is the last one for now as the practice exercises now be fully up to date.
=> leap: update doc

exercises/practice/sieve/sieve.h
old: "the number of calculate primes"
new: "the number of calculated primes"
=> sieve: fix a small typo

exercises/practice/secret-handshake/.approaches/config.json, exercises/practice/secret-handshake/.approaches/introduction.md, exercises/practice/secret-handshake/.approaches/iterate-once/content.md, exercises/practice/secret-handshake/.approaches/iterate-once/snippet.txt
Approach for Secret Handshake.
=> Secret Handshake approach

exercises/practice/sieve/.approaches/array-of-ones-and-zeros/content.md, exercises/practice/sieve/.approaches/array-of-ones-and-zeros/snippet.txt, exercises/practice/sieve/.approaches/config.json, exercises/practice/sieve/.approaches/introduction.md
=> Sieve approach

exercises/practice/binary-search/.approaches/config.json, exercises/practice/binary-search/.approaches/introduction.md, exercises/practice/binary-search/.approaches/while-with-if-statements/content.md, exercises/practice/binary-search/.approaches/while-with-if-statements/snippet.txt
=> Binary Search approach

exercises/practice/secret-handshake/.approaches/introduction.md, exercises/practice/secret-handshake/.approaches/iterate-once/content.md
Just a blank line added here and there
=> Secret Handshake minor format tweak

exercises/practice/pangram/.approaches/bitfield/content.md
Took a blank line out and put a couple blank lines in.
=> Pangram approach minor format tweaks

exercises/practice/grains/,approaches/bit-shifting/content.md, exercises/practice/grains/,approaches/bit-shifting/snippet.txt, exercises/practice/grains/,approaches/config.json, exercises/practice/grains/,approaches/introduction.md
=> Grains approach

exercises/practice/bob/.approaches/answer-array/content.md, exercises/practice/bob/.approaches/answer-array/snippet.txt, exercises/practice/bob/.approaches/config.json, exercises/practice/bob/.approaches/introduction.md
=> Bob approach

exercises/practice/resistor-color/.approaches/config.json, exercises/practice/resistor-color/.approaches/define-consecutive-values/content.md, exercises/practice/resistor-color/.approaches/define-consecutive-values/snippet.txt, exercises/practice/resistor-color/.approaches/introduction.md
An approach for Resistor Color.
=> Resistor Color approach

exercises/practice/isogram/.approaches/bitfield/content.md, exercises/practice/isogram/.approaches/bitfield/snippet.txt, exercises/practice/isogram/.approaches/config.json, exercises/practice/isogram/.approaches/introduction.md
=> Isogram approach

exercises/practice/hamming/.approaches/config.json, exercises/practice/hamming/.approaches/increment-pointers/content.md, exercises/practice/hamming/.approaches/increment-pointers/snippet.txt, exercises/practice/hamming/.approaches/introduction.md
=> Hamming approach

exercises/practice/collatz-conjecture/.approaches/bitwise-operations/content.md, exercises/practice/collatz-conjecture/.approaches/bitwise-operations/snippet.txt, exercises/practice/collatz-conjecture/.approaches/config.json, exercises/practice/collatz-conjecture/.approaches/introduction.md
Approach for Collatz Conjecture
=> Collatz Conjecture approach

config.json, exercises/practice/resistor-color/test_resistor_color.c
Addresses https://github.com/exercism/c/issues/840
=> Move resistor color to later in the track and bump the difficulty

exercises/practice/difference-of-squares/.approaches/config.json, exercises/practice/difference-of-squares/.approaches/formula/content.md, exercises/practice/difference-of-squares/.approaches/formula/snippet.txt, exercises/practice/difference-of-squares/.approaches/introduction.md
Approach for Difference of Squares
=> Difference of Squares approach

exercises/practice/armstrong-numbers/.approaches/config.json, exercises/practice/armstrong-numbers/.approaches/introduction.md, exercises/practice/armstrong-numbers/.approaches/log10-no-pow/content.md, exercises/practice/armstrong-numbers/.approaches/log10-no-pow/snippet.txt
Approach for Armstrong Numbers
=> Armstrong Numbers approach

exercises/practice/beer-song/.approaches/complexity-in-data/content.md, exercises/practice/beer-song/.approaches/complexity-in-data/snippet.txt, exercises/practice/beer-song/.approaches/config.json, exercises/practice/beer-song/.approaches/introduction.md
=> Beer Song approach

exercises/practice/two-bucket/.docs/instructions.md
- typo: "fulstack"
- http -> https
=> two-bucket: sync instructions with problem-specs

exercises/practice/acronym/.approaches/config.json, exercises/practice/acronym/.approaches/introduction.md, exercises/practice/acronym/.approaches/look-for-start-chars/content.md, exercises/practice/acronym/.approaches/look-for-start-chars/snippet.txt
=> Acronym approach

exercises/practice/darts/.approaches/config.json, exercises/practice/darts/.approaches/hypot-for-radius/content.md, exercises/practice/darts/.approaches/hypot-for-radius/snippet.txt, exercises/practice/darts/.approaches/introduction.md
=> Darts approach

exercises/practice/saddle-points/.docs/instructions.md, exercises/practice/saddle-points/.docs/introduction.md, exercises/practice/saddle-points/.meta/config.json
This addresses the issue reported by @tosiek88 in https://github.com/exercism/c/pull/893.
=> Sync saddle-points exercise

exercises/practice/sum-of-multiples/.docs/instructions.md, exercises/practice/sum-of-multiples/.meta/config.json
Fixes https://github.com/exercism/c/issues/896
=> Sync sum-of-multiples documentation

config.json, exercises/practice/reverse-string/.docs/instructions.md, exercises/practice/reverse-string/.meta/config.json, exercises/practice/reverse-string/.meta/example.c, exercises/practice/reverse-string/.meta/example.h, exercises/practice/reverse-string/.meta/tests.toml, exercises/practice/reverse-string/makefile, exercises/practice/reverse-string/reverse_string.c, exercises/practice/reverse-string/reverse_string.h, exercises/practice/reverse-string/test-framework/unity.c, exercises/practice/reverse-string/test-framework/unity.h, exercises/practice/reverse-string/test-framework/unity_internals.h, exercises/practice/reverse-string/test_reverse_string.c
Function and argument names, and test cases, are taken from
https://github.com/exercism/problem-specifications/blob/main/exercises/reverse-string/canonical-data.json
makefile and test-framework/* were copied from other exercises.
This is my first PR for exercism/c
https://forum.exercism.org/t/select-featured-exercises-for-jurassic-july/6018/9
closes #899
=> Add reverse-string exercise (#899)

exercises/practice/hello-world/hello_world.h, exercises/practice/hello-world/test_hello_world.c
In a previous version the solution was located in a director `src` and the tests in the `test` directory.  
That has been changed a while ago but the comments in the `hello-world` exercise have not been updated.
=> hello-world: Adjust locations of files in comments.

config.json
Related to https://github.com/exercism/c/pull/974
These hit around the same time as the original re-ordering but were not ordered according to their score.
=> Reorder new exercises

exercises/practice/resistor-color/.approaches/introduction.md
Was just going through the C track and got a 404 on this link, it works in singular.
=> Fix link to resistor-color approach

exercises/practice/queen-attack/.approaches/introduction.md
Markdown error along with some copy-pasta.
=> Fix link to queen-attack approach

exercises/practice/isogram/.approaches/config.json
This was copy/pasted from Go with a duplicate UUID.
=> Update duplicate UUID

exercises/practice/luhn/.docs/instructions.md, exercises/practice/luhn/.docs/introduction.md, exercises/practice/pascals-triangle/.docs/introduction.md
This pull request updates the documentation to align with the **Problem-Specification** repository. With this update, the entire track, including all exercise tests, is synced with the Problem-Specification repository for the time being, acknowledging that future changes may require additional updates.
=> Updating docs to sync with Problem-Specification

exercises/practice/anagram/.docs/instructions.md, exercises/practice/grains/.docs/instructions.md, exercises/practice/grains/.docs/introduction.md, exercises/practice/grains/.meta/config.json, exercises/practice/leap/.meta/config.json, exercises/practice/rna-transcription/.meta/config.json, exercises/practice/saddle-points/.docs/instructions.md, exercises/practice/say/.meta/config.json, exercises/practice/sieve/.docs/instructions.md
This PR updates the documentation and metadata for all exercises to align with the latest changes from the [problem-specifications](https://github.com/exercism/problem-specifications) repository.  
```sh
PS C:\Programming\Exercism\c> ./bin/configlet.exe sync   
Updating cached 'problem-specifications' data...
Checking exercises...
Every exercise has up-to-date docs, filepaths, metadata, and tests!
```
=> Sync docs and metadata to sync with with problem-specifications

.github/workflows/checks.yml, .github/workflows/format-code.yml, .github/workflows/test.yml, bin/check-include-guards, docs/CONTRIBUTING.md, exercises/practice/rna-transcription/.meta/example.c, exercises/practice/zebra-puzzle/.meta/example.c
Ubuntu 20.04 runners were disabled April 15th.
=> Move GitHub Actions to Ubuntu 24.04

exercises/practice/queen-attack/.approaches/introduction.md
=> Correct typo in introduction.md

config.json, exercises/practice/flower-field/.docs/instructions.md, exercises/practice/flower-field/.docs/introduction.md, exercises/practice/flower-field/.meta/config.json, exercises/practice/flower-field/.meta/example.c, exercises/practice/flower-field/.meta/example.h, exercises/practice/flower-field/.meta/tests.toml, exercises/practice/flower-field/flower_field.c, exercises/practice/flower-field/flower_field.h, exercises/practice/flower-field/makefile, exercises/practice/flower-field/test-framework/unity.c, exercises/practice/flower-field/test-framework/unity.h, exercises/practice/flower-field/test-framework/unity_internals.h, exercises/practice/flower-field/test_flower_field.c
https://forum.exercism.org/t/suggestion-deprecate-minesweeper-for-flower-field/17967/
=> Add `flower-field`, deprecating `minesweeper`

exercises/practice/secret-handshake/.meta/example.c, exercises/practice/secret-handshake/.meta/example.h, exercises/practice/secret-handshake/test_secret_handshake.c
Per our discussion in the [forum](http://forum.exercism.org/t/the-secret-handshaking-exercise-in-c-does-not-check-the-number-of-actions/18173/5), I have made the following changes to the Secret Handshake exercise.
- The previous version of tests let solutions with extra actions pass.
- The tests now require that each solution returns an array of size 4, and the unused slots of the array be filled with NULL.
- .meta/example.c has been revised suitably so that it passes all revised tests.
- Given the nature of the revision, I don't think that the existing solutions need to be re-checked.
[no important files changed]
=> Secret Handshake: Revised the tests and .meta/example.c.
