- hamming/rakefile.rb
- raindrops/rakefile.rb
Currently it is rather complicated to prepare the C track (see https://gist.github.com/7083c629a709b01f63fc). This patch prevents rather cryptic error messages like 
```
ERROR: Config filepath [:project][:build_root]['build'] does not exist on disk.
rake aborted!
/vagrant/exercism/c/vendor/ceedling/lib/ceedling/configurator.rb:265:in `validate'
/vagrant/exercism/c/vendor/ceedling/lib/ceedling/setupinator.rb:30:in `do_setup'
/vagrant/exercism/c/vendor/ceedling/lib/ceedling/rakefile.rb:46:in `<top (required)>'
/vagrant/exercism/c/vendor/ceedling/lib/ceedling.rb:66:in `load'
/vagrant/exercism/c/vendor/ceedling/lib/ceedling.rb:66:in `load_project'
/vagrant/exercism/c/raindrops/rakefile.rb:7:in `<top (required)>'
(See full trace by running task with --trace)
```
and it enables the user to type …
> let rake create required directories and enable rake without arguments

- exercises/hello-world/test/test_hello_world.c
- exercises/raindrops/test/test_raindrops.c
In exercises where the solution is written to a buffer, there should be a test for buffer overflows. Buffer overflows are a a common error source in C so we should help our users to avoid them.
> Add tests for buffer overflows

- exercises/anagram/test/test_anagram.c
- exercises/hello-world/test/test_hello_world.c
With -Werror=strict-prototypes functions without arguments must be
declared as "return_type function_name(void)". -Werror=strict-prototypes
is in the CFLAGS variable of the make files, though unused.
> Explicitely state when functions don't take args.

- SETUP.md
> Remove references to deprecated help.exercism.io

- exercises/anagram/makefile
- exercises/bob/makefile
- exercises/hamming/makefile
- exercises/hello-world/makefile
- exercises/leap/makefile
- exercises/raindrops/makefile
While practicing Hello World and Anagram, as I figured out what I was doing, I wanted to comment or uncomment tests. I expected that doing so would exclude or include those tests at runtime, but it didn't. Same problem as I was editing my solution. This commit tells `make` (for all exercises) that the compiled tests have dependencies on files in `src` and `test`, so that the tests get rebuilt when I expect.
> Recompile tests on any change to tests or code.

- exercises/anagram/src/anagram.h
Looks like a gremlin got left in when we changed this from `example.h` to `anagram.h`.
> Fixed include guard for Anagram.h

- config.json
- exercises/grains/makefile
- exercises/grains/src/example.c
- exercises/grains/src/example.h
- exercises/grains/test/test_grains.c
- exercises/grains/test/vendor/unity.c
- exercises/grains/test/vendor/unity.h
- exercises/grains/test/vendor/unity_internals.h
This was modeled after the C++ implementation, which uses 1-based indexing (e.g. `square(1)` returns 1).  However, I'm wondering if this is the best approach.  It certainly makes the tests read better, but we might be teaching the wrong lesson.  Most experienced C developers would consider square 0 to be the first square.
> Add 'grains' exercise

- exercises/leap/src/example.h
Fixes an implicit declaration warning due to the function being implemented as `is_leap_year` and called in the tests as `is_leap_year` but being declared as `leap_year` in the sample header.
Related to #62
> Fix compiler warning in Leap

- exercises/gigasecond/src/example.c
- exercises/gigasecond/src/example.h
- exercises/gigasecond/test/test_gigasecond.c
Converting the gigasecond exercise to use `struct tm` and `mktime()`.
This forcibly turns off Daylight Savings Time, which may have been a contributing factor for the problems we were seeing. (If I let my system choose what to use, the tests would fail ~25% of the time. I still have no clue as to why.)
Closes #66 
Closes #60
> Removing non-standard time functions.

- exercises/anagram/src/example.c
I believe this is the problem with the current anagram solution. For now I only spot fixed this one issue, but the rest of the problem may need to be looked at for improvements (#65 at least). If you guys think we should fix it up now I can go ahead, but this should let us get Travis up and running.
What I _think_ happened was the original `malloc` and `memcpy` threw away the null terminator. It would occasionally work if the next byte of memory was a null terminator and not otherwise. I should've just remembered to use valgrind, since that catches the overflow immediately.
> anagram: fixing strlen error

- .travis.yml
- README.md
- bin/run-tests
- exercises/anagram/makefile
- exercises/beer-song/makefile
- exercises/bob/makefile
- exercises/gigasecond/makefile
- exercises/grains/makefile
- exercises/hamming/makefile
- exercises/hello-world/makefile
- exercises/leap/makefile
- exercises/nth-prime/makefile
- exercises/pangram/makefile
- exercises/raindrops/makefile
- exercises/rna-transcription/makefile
My idea is just to have a shell script that will copy/rename the `example.c` and `example.h` files with the appropriate names and then execute `make` in each exercise directory.  I do not claim to know anything about bash scripts, so suggestions are greatly encouraged.
> Configure Travis task to execute tests for all examples

- exercises/hamming/src/example.c
- exercises/hamming/src/example.h
- exercises/hamming/test/test_hamming.c
- exercises/rna-transcription/src/example.c
- exercises/rna-transcription/test/test_rna_transcription.c
I cleaned up the `compute` interface by removing explicitly passed (and error-prone) string length and calculated with `strlen` instead.
Closes #41
> Remove explicitly passed string length in Hamming

- config.json
- exercises/allergies/makefile
- exercises/allergies/src/allergies.h
- exercises/allergies/src/example.c
- exercises/allergies/src/example.h
- exercises/allergies/test/test_allergies.c
- exercises/allergies/test/vendor/unity.c
- exercises/allergies/test/vendor/unity.h
- exercises/allergies/test/vendor/unity_internals.h
See https://github.com/exercism/x-common/tree/master/exercises/allergies
> Add 'allergies' exercise

- bin/run-tests
> Make run-test script fail if compilation has errors

- exercises/anagram/test/test_anagram.c
I cleaned up the test cases so they're more consistent. I could reduce the LOC by ~90 lines by using a macro to get rid of most of the boilerplate, but I felt that adding another layer of indirection would be too confusing.
Closes #65
> Refactoring anagram test cases.

- exercises/leap/test/test_leap.c
There was an extra, second, semi-colon at the end of an ASSERT line. This probably causes no harm but is nevertheless incorrect. This commit removes it.
> Remove spurious semi-colon

- exercises/gigasecond/test/test_gigasecond.c
Without this, using the code as-is, an error is given upon compilation:
~~~sh
$ make test
Compiling tests.out
test/test_gigasecond.c: In function ‘test_your_birthday’:
test/test_gigasecond.c:58:4: error: format not a string literal and no format arguments [-Werror=format-security]
printf(ctime(&gigday));
^~~~~~
cc1: all warnings being treated as errors
make: *** [tests.out] Error 1
~~~
> Add format string to printf in test_your_birthday

- exercises/grains/src/example.c
- exercises/grains/test/test_grains.c
A chess board does not have a zeroth square or more than 64 squares
> Add test for invalid indexes

- docs/LEARNING.md
The edit is to point the link to the root of the article, instead of the second page. I thought the article was really hard to follow, and poorly written. Turns out I was on the second page, which wasn't clear until getting to the end of the article.
> Link to first page of article

- exercises/space-age/src/example.c
- exercises/space-age/src/example.h
- exercises/space-age/test/test_space_age.c
I improved the code as suggested in the last [ pull request](https://github.com/exercism/xc/pull/122).
So there is only one function now, where you give the planet name (the value is defined in the header) and the number of seconds to get the result.
Is it a problem if the `#define` are in the header ?
> Improved code for space age

- exercises/react/src/example.c
The initial version of react (see #126) let the reactor store all cells
in a linked list, then blindly updated all cells whenever any cell was
set. This was correct but wasteful.
This commit rearchitects the example solution so that:
* reactors only keep track of the input cells
* all other cells keep track of their dependent compute cells
* only dependents get updated when a cell is set
Space cost of:
* one extra `struct child` allocated per compute2 cell created.
* one extra integer field per cell.
> react: Update only dependents of the just-set cell

- exercises/perfect-numbers/src/example.c
When running all the tests using bin/run-tests there is a notable pause while running perfect_numbers, so I made a small optimization to speed up the example solution.
This is totally unnecessary, but the new version is a better example solution for anyone that ends up looking at it.
> perfect_number: Optimize example solution

- config.json
- exercises/scrabble-score/makefile
- exercises/scrabble-score/src/example.c
- exercises/scrabble-score/src/example.h
- exercises/scrabble-score/test/test_scrabble_score.c
- exercises/scrabble-score/test/vendor/unity.c
- exercises/scrabble-score/test/vendor/unity.h
- exercises/scrabble-score/test/vendor/unity_internals.h
I implemented all the tests from canonical-data.json. I wasn't sure on difficulty, nor does it look like config.json is sorted by difficulty, so I used the rust implementation as reference.
> Add scrabble-score exercise

- README.md
The repo rename #148 broke the travis-ci links, this just points the README to the correct places in Travis.
> Update Travis-ci links with new repo name.

- README.md
We renamed x-common to problem-specifications a while back. The old links redirect, but it seems cleaner to replace them with the new links.
> Rename references to the problem-specifications repository

- docs/INSTALLATION.md
Visual Studio 2017 Community Edition is currently what is downloadable from that link, so it should reflect that change.
> Update INSTALLATION.md with Visual Studio version

- exercises/raindrops/test/test_raindrops.c
I am assuming this was an unintentional copy/paste error.  If it was intentional then reject this change.  If you let me know the pedagogical reason for running these tests twice I can add a comment, and my guess is we can get the same benefit just duplicating a couple.
> deleted duplicate test runs in raindrops

- exercises/acronym/src/example.c
- exercises/acronym/test/test_acronym.c
I added the test cases for nullptr and empty string to match the example implementation.  We can change the expected results and the example implementation if you want.  Second test should maybe return "", but either way is OK.
> Added test cases for nullptr and empty string to acronym

- exercises/hamming/src/example.c
- exercises/hamming/src/example.h
- exercises/hamming/test/test_hamming.c
These two tests were ambiguous:
```
void test_ignores_extra_length_on_first_strand_when_longer(void)
{
TEST_ASSERT_EQUAL(0, compute("AAAG", "AAA"));
}
void test_ignores_extra_length_on_other_strand_when_longer(void)
{
TEST_ASSERT_EQUAL(0, compute("AAA", "AAAG"));
}
```
The title says ignore extra length, but  completely ignoring two different length strands would also pass. 
I fixed so you had to compare the first 3 letters to pass.
I could also change so you had to drop.
A 3rd choice, that is a little more rework is to go back and return -1 for errors.
Let me know if you want one of the other choices.
> Updated unequal length tests in hamming

- exercises/robot-simulator/src/example.c
- exercises/robot-simulator/src/robot_simulator.h
- exercises/robot-simulator/test/test_robot_simulator.c
Update robot simulator exercise to snake case per #184 
Am unsure about enum members casing. IIRC the Linux kernel style is to use all-cap snake case, like:
```c
enum {
LIKE_THIS
}
```
But from memory I don't think any of the other exercises use this so have left all lower for now.
> Update robot simulator exercise to snake case

- README.md
- docs/CONTRIBUTING.md
- docs/C_STYLE_GUIDE.md
Start a contributing guide by collating information from the README and links to other relevant information. This allows us to extend the information beyond the scope of the README. Item in point, the CI information.
speaking of which, I don't actually know a huge amount about what Travis does (other than run the tests and indent check) so maybe someone else could contribute on that point in a more concise manner than I?
> Add a contributing guide

- exercises/triangle/src/example.c
- exercises/triangle/src/example.h
- exercises/triangle/test/test_triangle.c
The triangle exercise uses a pointer to a struct as the parameter to the functions that are to be implemented.
AFAICT there is no need for the parameter to be a pointer rather than the struct itself. As the exercise relates to structs rather than pointers, it seems an easy change to pass the structs by value to make it simpler to implement.
> Triangle: change parameter from pointer to a struct

- config.json
- exercises/sublist/README.md
- exercises/sublist/makefile
- exercises/sublist/src/example.c
- exercises/sublist/src/sublist.h
- exercises/sublist/test/test_sublist.c
- exercises/sublist/test/vendor/unity.c
- exercises/sublist/test/vendor/unity.h
- exercises/sublist/test/vendor/unity_internals.h
Problem specification: https://github.com/exercism/problem-specifications/tree/master/exercises/sublist
> Add sublist exercise

- exercises/phone-number/test/test_phone_number.c
Because blindly freeing a global pointer just screams scary to me. It's not really in this case, but having a dangling `free()` with no check and no zero'ing of the pointer might not be something we want the users to see.
> Adding memory safety to phone_number tests.

- exercises/sieve/test/test_sieve.c
Updated test to use the Unity macro.  Provides a better error message.  Checked for other test suites using memcmp, but there were none.
> Updated sieve to use TEST_ASSERT_EQUAL_UINT_ARRAY instead of memcmp

- config.json
Per #250, this changes the nesting of some exercises that were either nested too deep or not linked to the core of the track at all (i.e. floating).
I also took the opportunity to reorder the `config.json` listing to approximate the exercise ordering as it was starting to get a little hard to find related exercises.
The visualisation of the `config.json` now appears like so (see the linked issue for the visualisation as it was previously):
> Fix exercise nesting

- docs/C_STYLE_GUIDE.md
I have made some additions to the style guide based on previous issue and PR discussions.
Additions are:
- Specifying the C standard  and explicitly disallowing POSIX
- Prefer C99 standard  and standard fixed-width types
- Prefer pass by value parameters where appropriate
- Prefer const-qualified pointer parameters
> Update the style guide

- exercises/roman-numerals/test/test_roman_numerals.c
Aligns test_roman_numerals.c with new test case specified in https://github.com/exercism/problem-specifications/pull/1139
> roman-numerals: added test case "49" as per updated canonical-data.json

- config.json
- exercises/crypto-square/README.md
- exercises/crypto-square/makefile
- exercises/crypto-square/src/example.c
- exercises/crypto-square/src/example.h
- exercises/crypto-square/test/test_crypto_square.c
- exercises/crypto-square/test/vendor/unity.c
- exercises/crypto-square/test/vendor/unity.h
- exercises/crypto-square/test/vendor/unity_internals.h
Omitted error checking on 'calloc' to avoid over-bloating. The tests check already for 'NULL'. Interested to hear your thoughts about this (and about the whole solution of course).
> Implement exercise 'crypto-square'

- docs/C_STYLE_GUIDE.md
Test helper functions should come *after* `setup()` and `tearDown()`.
> Correct guide on order of test helper functions

- docs/SNIPPET.txt
I've changed the code snippet to appear more like a standard "Hello, World!" program, which can be compiled and run. I've also included a for loop to make use of the available space in the snippet box.
[Issue #303]
> Changed SNIPPET.txt to be a small standalone program

- exercises/isogram/test/test_isogram.c
In the current test set, a submission will pass if it only checks for
duplicates in the first 8 letters.
> Added test for duplicated letter past 'h'.

- exercises/complex-numbers/makefile
- exercises/complex-numbers/src/example.c
- exercises/complex-numbers/test/test_complex_numbers.c
Fixes #326 
Turns out that Unity uses `float`s by default, but the complex numbers exercise uses `double`s. This results in false negatives for all checks that use floating point numbers. After configuring Unity properly, I verified that incorrect implementations are correctly flagged. In fact, this reveals errors in the sample implementation that still need to be fixed.
Thanks @Zialus for finding this issue!
> Fix complex tests by configuring Unity to use doubles instead of floats

- exercises/acronym/test/test_acronym.c
See #320
The issue involves not allocating enough space for the result, so `make test` may succeed, and the problem would only show up in `make memcheck`.
> acronym: Added test for long abbreviation

- exercises/grains/test/test_grains.c
Closes #334 
This avoids using `TEST_ASSERT_EQUAL_UINT64` which is problematic on 32-bit systems (for whatever reason). Instead it uses the generic `TEST_ASSERT` which only evaluates a bool.
> Use generic assertion for u64s

- exercises/gigasecond/test/test_gigasecond.c
Use a direct implementation of construct_date.
This avoids issues with mktime().
timegm() not used as not universal.
All tests pass with standard solution.
> gigasecond: Addresses: 319

- bin/fetch-configlet
- bin/run-tests
- bin/verify-indent
- indent.sh
`#!/usr/bin/env bash` is supposed to be more portable than directly linking to /bin/bash.
I hit this while running on NixOS.
> Updating shebang for better portability.

- exercises/binary-search-tree/src/example.c
- exercises/binary-search-tree/src/example.h
- exercises/binary-search-tree/test/test_binary_search_tree.c
I think it's bad the solution doesn't require freeing the tree for two reasons:
1. It's not hard to implement, and does teach something
2. I general it's a good habit to provide a free function, as I might allocate with a different function.
> moved the free function

- exercises/nucleotide-count/test/test_nucleotide_count.c
The unit tests for nucleotide-count contained the filename for a
different exercise (rna-transcription).
> Fix filename in nucleotide-count tests.

- config.json
With giga-second being unhelpful and considered a clutter by myself, I suggested to swap it with word-count being harder but leaving room for improvement as the student might be publishing more iterations than with giga second. See issue #353 for clarifying situation.
> moved the gigasecond towards the side exercises to move word-count to core tracks

- exercises/word-count/test/test_word_count.c
This catches a fairly common off-by-one error.
See issue #359.
> word-count: Changed excessive word test from 23 to 21 words.

- .gitignore
- bin/run-tests
- docs/CONTRIBUTING.md
Modifies the `bin/run-tests` script to use out of tree builds, and to allow running a subset of tests to improve development.
I verified POSIX compat using https://github.com/koalaman/shellcheck, which we can add to Travis easily if needed (there are warnings in both `verify-indent` and `fetch-configlet` that should probably be fixed if we enable it).
> Moving to out of tree builds.

- .travis.yml
- bin/fetch-configlet
- bin/verify-indent
- indent.sh
This adds a [ShellCheck](https://github.com/koalaman/shellcheck) static analysis run to lint the bash scripts under bin/. Travis has it installed by default, so it can be invoked pretty easily.
> Adding ShellCheck linter to Travis.

- config.json
This regex needs to match the test file path starting from the root of the exercise's directory. This is to fix the issue described in exercism/exercism#4797 where we were displaying the contents of the unit test framework on the website.
I _believe_ this is right but I'm not quite sure how I could test this without just merging it and watching the rollout to see if I broke it. It's pretty low impact, so it might be easiest just to merge it, babysit the change and then patch it quickly if it broke. The website is pretty much live with HEAD so it could be handled pretty quick.
> Adding test_pattern to config.json

- exercises/isogram/test/test_isogram.c
Without this test, you can pass all tests while ignoring everything after the first non-letter character.
> isogram: Add test case for duplicates following non-letter character

- exercises/allergies/src/allergies.h
- exercises/allergies/src/example.c
- exercises/allergies/src/example.h
- exercises/allergies/test/test_allergies.c
Closes #321 
This removes all the heap allocations from the allergies exercise. I also simplified the exercise by just switching to using an array of bools for output instead of an array of allergen values so that it more directly demonstrates how you can think of a bitfield as an array of bools.
I explicitly did _not_ update this to the [new test suite](https://github.com/exercism/problem-specifications/blob/master/exercises/allergies/canonical-data.json) since that would require a full overhaul of the tests, and this change is intended to just address the present concerns.
> Allergies: Use stack allocated arrays.

- exercises/word-count/.meta/hints.md
- exercises/word-count/README.md
- exercises/word-count/test/test_word_count.c
Per #357, have changed test to use `TEST_ASSERT_EQUAL_STRING_LEN` test assert instead of `TEST_ASSERT_EQUAL_UINT8_ARRAY`.
Change is still under discussion on the issue, so have marked as WIP for now.
> word-count: change to TEST_ASSERT_EQUAL_STRING_LEN() in tests

- bin/run-tests
Currently the run-tests bash script clones all exercises to a build, even when only running specific exercises. (e.g. `$ ./bin/run-tests acronym beer-song`)
This PR adjusts the script to only copy the exercises selected for testing.
> run-tests: clone only necessary exercises

- exercises/sieve/src/example.c
- exercises/sieve/src/sieve.h
- exercises/sieve/test/test_sieve.c
Rationale:
- Signature used relied on some array of fixed size
- Types used are rather arbitrary
- Test cases exhibited bad style
> Update the *sieve* exercise.

- config.json
- exercises/resistor-color/README.md
- exercises/resistor-color/makefile
- exercises/resistor-color/src/example.c
- exercises/resistor-color/src/example.h
- exercises/resistor-color/src/resistor_color.c
- exercises/resistor-color/src/resistor_color.h
- exercises/resistor-color/test/test_resistor_color.c
- exercises/resistor-color/test/vendor/unity.c
- exercises/resistor-color/test/vendor/unity.h
- exercises/resistor-color/test/vendor/unity_internals.h
Towards #390
Again, Unity does not have an assert for the implementation defined type, `enum` in this case.
Add to https://github.com/ThrowTheSwitch/Unity/issues/437 regarding this.
Plan to follow up with `resistor-duo` and  `resistor-color-trio` as non-core exercises unlocked by this one
> resistor-color: add exercise

- config.json
- exercises/saddle-points/README.md
- exercises/saddle-points/makefile
- exercises/saddle-points/src/example.c
- exercises/saddle-points/src/example.h
- exercises/saddle-points/src/saddle_points.c
- exercises/saddle-points/src/saddle_points.h
- exercises/saddle-points/test/test_saddle_points.c
- exercises/saddle-points/test/vendor/unity.c
- exercises/saddle-points/test/vendor/unity.h
- exercises/saddle-points/test/vendor/unity_internals.h
Towards #390 
Two issues:
1. `verify-indent` will probably fail. I ran `indent -linux -i3 -nut`, `indent.sh` and `verify-indent` locally. The commands all ran, but `verify-indent` keeps telling me there's some issue.
2. Unity has no test for values of type `size_t`. I have opened an issue on the Unity repository in this regard (https://github.com/ThrowTheSwitch/Unity/issues/437), but in the meantime do we:
1. Compromise on type and use `uint8_t` for array indices
2. Compromise on cross-platform correctness and test as if `uint64_t`?
> saddle-points: add exercise

- config.json
- exercises/square-root/.meta/description.md
- exercises/square-root/README.md
- exercises/square-root/makefile
- exercises/square-root/src/example.c
- exercises/square-root/src/example.h
- exercises/square-root/src/square_root.c
- exercises/square-root/src/square_root.h
- exercises/square-root/test/test_square_root.c
- exercises/square-root/test/vendor/unity.c
- exercises/square-root/test/vendor/unity.h
- exercises/square-root/test/vendor/unity_internals.h
Adds a new exercise to calculate the square root of a natural radicand.
Because the tests use only natural numbers up to 255, the exercise can be implemented via a simplified algorithm that uses bit shifting.
Will add readme after exercise addition PR is merged in problem specifications.
> square-root: add exercise

- exercises/armstrong-numbers/src/example.c
- exercises/armstrong-numbers/src/example.h
- exercises/armstrong-numbers/test/test_armstrong_numbers.c
- exercises/darts/src/example.c
- exercises/resistor-color-duo/src/example.c
- exercises/resistor-color-duo/src/example.h
- exercises/resistor-color-duo/test/test_resistor_color_duo.c
- exercises/resistor-color-trio/src/example.c
- exercises/resistor-color-trio/src/example.h
- exercises/resistor-color-trio/test/test_resistor_color_trio.c
- exercises/resistor-color/src/example.c
- exercises/resistor-color/src/example.h
- exercises/resistor-color/test/test_resistor_color.c
As noticed by  @gabriel376 on #413, I've been using the wrong style for function names 🤦‍♂ .
This PR updates them.
(I've only checked on the exercises that I've introduced, there may still be other occurrences of this in the repo).
> Correct function name style

- exercises/anagram/test/test_anagram.c
- exercises/clock/test/test_clock.c
- exercises/collatz-conjecture/test/test_collatz_conjecture.c
- exercises/largest-series-product/test/test_largest_series_product.c
- exercises/linked-list/test/test_linked_list.c
- exercises/raindrops/test/test_raindrops.c
- exercises/robot-simulator/test/test_robot_simulator.c
I noticed that a few other exercises also had incorrect arguments passed to the `UnityBegin()` call.
This PR corrects them.
To paraphrase the Pokémon theme: hope I've caught 'em all!
> Correct incorrect arguments to UnityBegin()

- config.json
- exercises/list-ops/README.md
- exercises/list-ops/makefile
- exercises/list-ops/src/example.c
- exercises/list-ops/src/example.h
- exercises/list-ops/src/list_ops.c
- exercises/list-ops/src/list_ops.h
- exercises/list-ops/test/test_list_ops.c
- exercises/list-ops/test/vendor/unity.c
- exercises/list-ops/test/vendor/unity.h
- exercises/list-ops/test/vendor/unity_internals.h
This implementation uses a different, simpler, backing structure than in #423.
Still does not implement or test concatenation - for the same reasons.
Have provided the definitions in the header as I think this is the first exercise that uses function pointers.
If this approach is preferred then #423  can be closed.
> list-ops: add exercise

- exercises/armstrong-numbers/src/armstrong_numbers.h
This PR is simultaneously an issue, and a potential fix for that issue.
I've been going through these exercises with a couple friends, serving as their offline mentor while they go through these. Right off the bat we came to recognize that some of the exercises are shipped with the function declaration in the header, and others aren't.
It's particularly frustrating for them, since they're so new to the language, and they're not accustomed to the way GCC can throw ten or more errors, most not particularly informative, ( eg. "what's an empty translation unit?" ).
I thought I'd try and contribute and ask for some more strict standards on the C track. For example:
1. Function declarations in the header should either be there for all exercises or for none.
2. A central decision on types. If …
> armstrong-numbers: added function declaration

- exercises/list-ops/test/test_list_ops.c
The current solution only compares the length of the arrays, and never compares the contents.
The first two arguments to `TEST_ASSERT_EQUAL_MEMORY_ARRAY` are cast to pointers, and internally Unity doesn't access the memory locations if the pointers are equal, so we don't get the crashes you'd expect from accessing invalid addresses.
Also added a message here, because Unity's error messages are not exactly useful.
Pointed out on slack - https://exercism-team.slack.com/archives/CATCU7LSJ/p1573889084013200
> list-ops: Compare array contents

- exercises/list-ops/src/example.c
- exercises/list-ops/test/test_list_ops.c
The type signature for `reverse_list()` suggests the function should return a new `list_t` but the tests don't actually test the return value; only the same list that is passed to `reverse_list()`.
> list-ops: Check return value of reverse_list()

- bin/fetch-configlet
Shamelessly dupes @coriolinus' fix: https://github.com/exercism/rust/pull/929
"Looks like Github has recently started returning non-uppercased
HTTP headers, at least some of the time. This broke the script,
which looked for a case-sensitive 'Location' header to find the
newest version. We can see this problem in spurious build failures like this."
"This fixes the script such that it no longer cares whether the initial
L is capital or not, and if it breaks again in the future, it will
give a more informative error."
> Fix fetch-configlet script

- config.json
Removes most string exercises from C track's "core" to reduce redundancy
and to minimize track pains. See issue #390 on GitHub for more detail.
"isogram" and "phone-number" preserved as core string exercises with
simple interfaces.
Demoted for specific complaints:
* palindrome-products
* word-count
While I initially proposed "atbash cipher" and "scrabble score" as possible candidates for the "advanced" string exercise, I realized "phone number" is a more "exemplary" exercise as it asks people to do a genuinely challenging task, and one they might realistically face (as it is "formatting input correctly or erroring"), but in a straightforward way that hopefully is easy to mentor. Also, because I mentioned "isogram" and "word-count", but word-count has specific complaints voiced against it, …
> Demote redundant string exercises from core

- exercises/hello-world/src/hello_world.c
- exercises/hello-world/src/hello_world.h
- exercises/hello-world/test/test_hello_world.c
Closes #392 
Have added inline comments inspired by the examples from other tracks linked on the referenced issue.
Have also changed the example function definition to now have a valid return statement, so that the first build does not fail (required adding `#include <stddef.h>` for `NULL`).
Also moved the `#include <stddef.h>` out of the test file as it is not used there
> hello-world: Add explanatory comments

- exercises/word-count/test/test_word_count.c
Added another memset for actual_solution on each test.
Not clearing it results on the tests failing when a test has less unique words than the previous one (unless the user clears the struct).
> word_count: Clear actual_solution on every test.

- exercises/anagram/test/test_anagram.c
A solution which sums each char on the word and compares the sum
will pass all tests because no words tested have a char combination
that sum the same as another word.
*   Provide an adversarial example for that situation.
*   Test is ignored after creating the candidates
so it will not cause segfault when ignored.
> anagram: Add test for non anagrams.

- exercises/rational-numbers/test/test_rational_numbers.c
All tests where zero is expected have denominator 1.
The test provides an invalid value and maybe should fail
because a rational number with 0 denominator is undefined.
> rational-nubers: Test a real rational zero.

- exercises/pascals-triangle/test/test_pascals_triangle.c
I normally expect a sequence of arrays to have all the same size, but enforcing that by reading `size` elements from each row in the result feels overly restrictive.  It prohibits a solution that mallocs just big enough arrays for each row, and it prohibits a solution like the following without this modification:
``` c
static void build_rows(size_t **triangle, size_t size)
{
if (!triangle) {
return;
}
// Initialize the first row
triangle[0][0] = 1;
// Build each row from the values of the last row.
for (size_t i = 1; i < size; ++i) {
// First value
triangle[i][0] = 0 + 1;
// Pairwise summation of previous row for the middle values, ie. nextRow
for (size_t j = 1; j < i; ++j) {
triangle[i][j] = triangle[i - 1][j - 1] + triangle[i - 1][j];
}
// Last value
triangle[i][i] = 1 + 0;
}
}
static …
```
> Pascal's Triangle: keep inner loop in `check` inside triangle bounds

- exercises/list-ops/test/test_list_ops.c
-  A defective new_list function can pass most tests
provided it always returns the same output.
-  This fix tests for the expected contents
instead of relying on user provided function.
> list-ops: Make list test independent of user.

- exercises/square-root/src/example.c
- exercises/square-root/src/example.h
- exercises/square-root/test/test_square_root.c
Functions in other exercises use `snake_case` but square root used `camelCase`. This switches `squareRoot` to `square_root` to be consistent with other exercises.
> Improve consistency in square root naming

- exercises/palindrome-products/test/test_palindrome_products.c
Test typo meant the same expression on both sides of the '&&', meaning that only one ordering of factors would be allowed.
Previous implementation did correctly not let failing implementation pass but would fail a subset of passing implementations due to enforcing factor ordering where none is needed.
> palindrome-products: make tests check factors that are in different orders

- exercises/pangram/.meta/tests.toml
- exercises/pangram/test/test_pangram.c
Resolves #515 
- Updates names for existing test cases to align closer to what's in canonical data
- There was also a test marked as missing but it looks like that test already exists so I've uncommented that line in `.meta/tests.toml`
Reference: [pangram `canonical-data.json`](https://github.com/exercism/problem-specifications/blob/master/exercises/pangram/canonical-data.json)
> pangram: Update to most recent canonical data

- exercises/isogram/.meta/tests.toml
- exercises/isogram/test/test_isogram.c
Resolves #506 
- Updates names for existing test cases to align closer to what's in canonical data
- Unskip tests in `.meta/tests.toml` that are already accounted for
Reference: [isogram `canonical-data.json`](https://github.com/exercism/problem-specifications/blob/master/exercises/isogram/canonical-data.json)
Test output with `TEST_IGNORE`s in `test_isogram.c` commented out:
```sh
$ make test
Compiling tests.out
test/test_isogram.c:100:test_empty_string:PASS
test/test_isogram.c:101:test_null:PASS
test/test_isogram.c:102:test_isogram_with_only_lower_case_characters:PASS
test/test_isogram.c:103:test_word_with_one_duplicated_character:PASS
test/test_isogram.c:104:test_word_with_one_duplicated_character_from_end_of_alphabet:PASS
test/test_isogram.c:105:test_longest_reported_english_isogram:PA …
```
> isogram: Sync to latest canonical exercise data

- .github/workflows/format-code.yml
Fixes #472 
cc @elyashiv 
There's an example commit where the use of this is demonstrated, on my fork of this repo, here: https://github.com/wolf99/c/pull/2
> Add repo code formatting in CI

- exercises/beer-song/.meta/tests.toml
- exercises/beer-song/src/beer_song.h
- exercises/beer-song/src/example.c
- exercises/beer-song/src/example.h
- exercises/beer-song/test/test_beer_song.c
fixes #497 
The test that checks for all verses in one go requires a string that is greater than the length that C allows for strings.
Rather than muck around with memory allocations I've just left it out and set it to false in the TOML, as it seems like it wouldn't add much.
Another thing I haven't updated, is the change from new-line delimited strings to string arrays for the output. Because the scale of the change required vs the impact seemed not worth it. I may look at it again soon though.
> beer-song: align with specification per #497

- exercises/complex-numbers/.meta/tests.toml
- exercises/complex-numbers/makefile
- exercises/complex-numbers/test/test_complex_numbers.c
Fixes #501 
The inputs in the added test can result in a rounding error.
To avoid this failing tests I have adjusted how the tests operate.
Instead of performing a floating-point test for equality,
it now performs a double comparison that passes if the actual
value is within some delta.
This comparison-with-delta method is usually considered
best practice when working with either float point values in C.
To enable this there is an extra flag added to the `makefile`
to enable double-precision operations in the testing framework.
> complex-numbers: align with specification per #501

- exercises/hamming/.meta/tests.toml
- exercises/hamming/test/test_hamming.c
Fixes #504 
Again here the question of semantics in the spec.
Does empty mean a zero-length string (i.e. ""), or NULL?
> hamming: align with specification per #504

- exercises/rail-fence-cipher/.meta/tests.toml
- exercises/rail-fence-cipher/src/example.c
- exercises/rail-fence-cipher/test/test_rail_fence_cipher.c
- Refactor remove helper function that has only one line
- Match `msg` argument name to spec
fixes #519
> rail-fence-cipher: align with specification per #519

- exercises/wordy/.meta/tests.toml
- exercises/wordy/test/test_wordy.c
Fixes #530 
Interesting to see the x-macros in the `example.c`. I think it's the only "real-world"  use of them that I have seen, that does not involve enumerations, for a very long time!
> wordy: align with specification per #530

- .github/workflows/build.yml
CI is currently failing. 
This is because the track has moved to v3, but the v2 configlet is run by files not overwritten by the v3 files.
this change removes the v2 configlet run from the `build.yml` leaving only the new v3 configlet run in `configlet.yml`.
> Remove v2 configlet use

- bin/check-unitybegin
- bin/run-tests
- bin/verify-unity-version
The root cause was that exercises moved from `exercises/*` to `exercises/practice/*` which broke scripts that searched in `exercises/*`
> Fix check-unitybegin, check-unity-version, run-tests

- docs/ABOUT.md
- docs/INSTALLATION.md
- docs/LEARNING.md
- docs/RESOURCES.md
- docs/TESTS.md
- docs/VERSIONS.md
- exercises/practice/square-root/.meta/description.md
- exercises/practice/word-count/.docs/instructions.append.md
We've defined a [specification for Markdown files](https://github.com/exercism/docs/blob/main/contributing/standards/markdown.md) to be applied Exercism-wide. This standard includes, amongst others, the following two rules:
- All files must start start with a level-1 heading (`# Some heading text`)
- No heading may decend a level greater than one below the previous (e.g. `## may only be followed by ###, not ####`)
This PR applies the above two rules to the Markdown documents in this repo. 
https://github.com/exercism/v3-launch/issues/17
> [v3] Update Markdown files to latest spec

- reference/README.md
It was here: https://github.com/exercism/v3/tree/main/languages/c/reference
I think this should not stay here, with the new structure coming; but it is useful to have to work with for some time until v3 launches.
> Rescue the list of concepts from the old v3 repo

- exercises/practice/square-root/.meta/tests.toml
`tests.toml` was missing from this exercise somehow
> square-root: add tests.toml

- exercises/practice/roman-numerals/.meta/tests.toml
- exercises/practice/roman-numerals/test_roman_numerals.c
Fixes #524 
Impossible to align with specification as it contains logical inconsistencies.
There is an issue raised for this here: https://github.com/exercism/problem-specifications/issues/1769
This PR should remain in draft status until the above issue is resolved.
> roman-numerals: align with specification per #524

- exercises/practice/linked-list/.meta/example.c
- exercises/practice/linked-list/.meta/example.h
- exercises/practice/linked-list/.meta/tests.toml
- exercises/practice/linked-list/linked_list.c
- exercises/practice/linked-list/linked_list.h
- exercises/practice/linked-list/test_linked_list.c
Updates linked list to the current spec.
A question to consider when reviewing: two of the functions in the example implementation return values that are never checked. This is because while it is idiomatic in C to return these, the test specification does not have any need to specify them as expected - do we test them or leave them as-is?
1. The benefit of leaving them untested is conformance to the spec and leaving a wider solution space.
2. The benefit of testing them is communicating C idioms to the student and being slightly more specific. (however, see below)
The functions in question:
``` c
struct list_node *list_push(struct list * list, ll_data_t data);
struct list_node *list_unshift(struct list * list, ll_data_t data);
```
If we are to test them:
- Do we add this for every use of …
> Linked list

- .gitignore
The `fetch-canonical-data-syncer` script is obsolete as canonical data syncing is now built into `configlet`.
See https://github.com/exercism/configlet/issues/124
> Remove canonical data syncer reference

- exercises/practice/hamming/.meta/tests.toml
I think this was introduced because of the changes to remove `incude = true`
Either way, duplicate keys cause configlet to throw an exception, so this change prevents that also
> hamming: remove duplicate key

- exercises/practice/list-ops/list_ops.h
Renamed list_value_t to list_element_t in the header of the list-ops exercise
> Rename a typedef in list-ops

- exercises/practice/grade-school/.meta/example.c
- exercises/practice/grade-school/.meta/tests.toml
- exercises/practice/grade-school/test_grade_school.c
> grade-school: align with specification per #503

- exercises/practice/robot-simulator/.meta/config.json
Configlet is failing in CI because it expects a valid value for `source_url` (https://github.com/exercism/c/runs/3667565364?check_suite_focus=true).
Same solution was used in #688
> robot-simulator: remove blank source_url

- exercises/practice/say/test_say.c
`ans` would not be freed on failed `TEST_ASSERT_XXX`, according to `make memcheck` on my local machine. Used `test_phone_number.c` as my guide for the fix.
> Update test_say.c  Fixed memory leaks

- exercises/practice/roman-numerals/test_roman_numerals.c
In current configuration `make memcheck` reported direct memory leak for failed `TEST_ASSERT_EQUAL_STRING` on my local machine (Ubuntu WSL.) With the updated configuration there are no memory leaks. Specifying `if (result) free result;` generated an error for attempted double free of `result`, so it must be getting successfully freed somewhere as long as the ASSERT passes. **Edit** I had forgotten to set `result` to NULL, which seems to have led to the double-free.
> Update to test_roman_numerals.c Fixed memory leaks

- exercises/practice/acronym/test_acronym.c
`make memcheck` reported direct memory leak on failed `TEST_ASSERT_EQUAL_STRING` on my local machine (Ubuntu WSL.) Now has no memory leaks.
> Update test_acronym.c Fixed memory leaks

- exercises/practice/pig-latin/test_pig_latin.c
`make memcheck` reported direct memory leak on failed `TEST_ASSERT_EQUAL_STRING` on my local machine (Ubuntu WSL.) Now reports no memory leaks.
> Update test_pig_latin.cs Fixed memory leaks

- exercises/practice/pascals-triangle/test_pascals_triangle.c
Very similar to previous fixes on other tracks. A difference is that the student allocates an array of arrays and is responsible for freeing all of that. Failing test ASSERTS were leaking memory.  Now failed ASSERTS do not leak memory.  No double-free on success. Of course, if a student allocates something else we don't expect, we can't catch it and the leak is on them, so to speak. 😄
> Update tests_pascals_triangle.c:  Fix memory leaks

- exercises/practice/list-ops/test_list_ops.c
Was leaking memory on failed ASSERTS. Students can't set lists persistently to NULL, since the delete_list function is only given the pointer to a list, not the address of the pointer, so if delete_list set the pointer to NULL it would only be setting the copy of the pointer to NULL. So now we set the list pointer to NULL in a variadic function that is passed all the lists needing to be deleted, which makes tests with multiple lists a bit less verbose. So, the student frees the list, we set it to NULL, and there is no memory leak on fail and no double-free on success.
> Update test_list_ops.c: Fixed memory leaks

- exercises/practice/diamond/.meta/example.c
- exercises/practice/diamond/.meta/example.h
- exercises/practice/diamond/diamond.h
- exercises/practice/diamond/test_diamond.c
As discussed in issue #758 this exercise currently requires the function `make_diamond()` to return an array of `char *` where the first element is a dynamically allocated string, and the other elements point to substrings of that first element.
That might be clever because it avoids unnecessary allocations, but it's not obvious.
This PR adds a second function `free_diamond()` as part of the exercise.
That way the students can choose how the result is allocated and are responsible for deallocating it completely.
That should be a little bit easier to understand. And it still allows the "clever" solution.
> Improve "diamond" by adding a cleanup function.

- concepts/conditionals/about.md
- concepts/pointers/about.md
- reference/exercise-concepts/resistor-color.md
A small PR that fixes some spelling.
qq: What's `typefdef` ? Is it actually spelled that way?
> Fix spelling

- .github/workflows/checks.yml
As discussed on #782 a simple User Agent fix would help resolve build errors for lychee-actions
```bash
[c] curl -I -H 'user-agent: lychee/0.9.0' https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
HTTP/2 403
x-azure-ref: 0OKFVYgAAAAB6pZomkF2ESoOnq6KwAjElQk9NMDJFREdFMDkyMQA1OTZkNzhhMi1jYTVmLTQ3OWQtYmNkYy0wODM1ODMzMTc0YjI=
accept-ranges: bytes
date: Tue, 12 Apr 2022 15:56:40 GMT
via: 1.1 varnish
x-served-by: cache-bom4746-BOM
x-cache: MISS
x-cache-hits: 0
x-timer: S1649779001.872762,VS0,VE5
strict-transport-security: max-age=31557600
[c] curl -I -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36' https://docs.github.com/en/actions/using-github-hosted-runners/about-github-h …
```
> lychee-action: add user-agent to prevent 403s

- exercises/practice/pig-latin/test_pig_latin.c
The order of the expected and the actual strings were revered giving a
error message where the output of the function was referred to as
expected.
Ex:
```
test_word_beginning_with_a:FAIL: Expected 'apple' Was 'appleay'
```
Now the message is:
```
test_word_beginning_with_a:FAIL: Expected 'appleay' Was 'apple'
```
Note: in both these examples the function under test just retunes the
input string.
> Updated call to assert to provide a better error

- exercises/practice/react/.meta/example.c
- exercises/practice/react/react.h
I was reviewing a submission for `reactor` and noticed that it used an empty argument list (`()`) instead of `(void)` for the `create_reactor` prototype and traced this back to the provided template.
This changes the template and sample solution to use the more correct `(void)`.
For more background, please see https://stackoverflow.com/questions/51032/is-there-a-difference-between-foovoid-and-foo-in-c-or-c
> Use (void) for create_reactor prototype

- docs/CONTRIBUTING.md
I noticed this link was broken on the last dependabot PR (https://github.com/exercism/c/pull/808).
I figure Wikipedia will be a more stable link.
> Fix include guard link

- exercises/practice/grains/test_grains.c
Currently the tests compare the expected and actual result with `==` and
call `TEST_ASSERT()` which leads to error messages like
"FAIL: Expression Evaluated To FALSE".
With `TEST_ASSERT_EQUAL_UINT64()` the error message is much easier to
understand:
"FAIL: Expected 18446744073709551615 Was 18446744073709551614"
> grains: Improve the tests with an _EQUAL_ macro.

- exercises/practice/armstrong-numbers/.meta/tests.toml
Adds 2 new tests as excluded in the exercise's `tests.toml` using `include = false`.
The tests are excluded because the track currently uses C99 which does not have an integer data type large enough to handle the Armstrong numbers these tests require (128 bits).
C23 will, or does (I am not sure of the current status of C23), have `_BitInt(N)` which would allow 128 bits. So this may be a (admittedly minor) case for #812.
Another alternative would be to change the interface to either allow the value to be split across multiple parameters, or to allow the value split across multiple members of a single struct parameter.
IMHO, these alternatives involve more complication than is expected in this exercise so I have choseen to simply exclude the tests for now.
> armstrong-numbers: update tests.toml

- exercises/practice/gigasecond/.meta/tests.toml
- exercises/practice/gigasecond/test_gigasecond.c
Adds test as excluded, see comment in `tests.toml`.
Also fixes 2 typos in the comments in the tests
> gigasecond: update tests

- exercises/practice/matching-brackets/.meta/tests.toml
- exercises/practice/matching-brackets/test_matching_brackets.c
Adds new test `test_paired_and_wrong_nested_brackets_but_innermost_are_correct()`, per the updated problem spec
> matching-brackets: update test

- exercises/practice/roman-numerals/.meta/example.c
- exercises/practice/roman-numerals/.meta/tests.toml
- exercises/practice/roman-numerals/test_roman_numerals.c
Adds tests per the updated problem spec.
This one required a small change to the example implementation to use a longer string when constructing the return value as the maximum expected return value is now longer with the new tests.
> roman-numerals: update tests

- exercises/practice/binary-search/.meta/example.c
- exercises/practice/binary-search/.meta/example.h
- exercises/practice/binary-search/binary_search.h
Currently in `binary-search` we pass an array via a `const` pointer but then expect a non-`const` pointer back. This requires an illegal cast (removal of `const`) as seen in our example.
This changes the return type from `int *` to `const int *` so that no cast is required.
> Binary Search - Do not expect a non-const pointer from a const pointer

- config.json
- exercises/practice/high-scores/.docs/instructions.append.md
- exercises/practice/high-scores/.docs/instructions.md
- exercises/practice/high-scores/.meta/config.json
- exercises/practice/high-scores/.meta/example.c
- exercises/practice/high-scores/.meta/example.h
- exercises/practice/high-scores/.meta/tests.toml
- exercises/practice/high-scores/high_scores.c
- exercises/practice/high-scores/high_scores.h
- exercises/practice/high-scores/makefile
- exercises/practice/high-scores/test-framework/unity.c
- exercises/practice/high-scores/test-framework/unity.h
- exercises/practice/high-scores/test-framework/unity_internals.h
- exercises/practice/high-scores/test_high_scores.c
Function names, and test cases, are taken from
https://github.com/exercism/problem-specifications/blob/main/exercises/high-scores/canonical-data.json
For simplicity, the following properties from the canonical test cases are omitted:
- scores
- latestAfterTopThree
- scoresAfterTopThree
- latestAfterBest
- scoresAfterBest
closes #901
> Add high-scores exercise (#901)

- exercises/practice/high-scores/test_high_scores.c
This change reverses the order of the actual and expected arguments for two tests so the assertion failure message makes more sense.
> Correct order of assertion arguments in high-scores (#907)

- exercises/practice/high-scores/test_high_scores.c
On #908  I noticed a small inconsistency nit in the ordering of parameters for the `check_personal-top_three()` function.
This change means that expected values arguments are always first in the parameter list for the function calls used within all `test_*` functions.
> Reorder parameters for consistency

- exercises/practice/hello-world/hello_world.c
@ErikSchierboom Could you please:
1. Check this is correct / get it over the line
2. Grep all other Hello Worlds and check that they all contain the word "Mars" and fix any that don't.
Thanks :)
> Hello World should start with the default stub

- exercises/practice/acronym/.approaches/look-for-start-chars/content.md
- exercises/practice/beer-song/.approaches/complexity-in-data/content.md
- exercises/practice/binary-search/.approaches/while-with-if-statements/content.md
- exercises/practice/hamming/.approaches/increment-pointers/content.md
- exercises/practice/isogram/.approaches/bitfield/content.md
- exercises/practice/linked-list/.approaches/circular-doubly-linked-list/content.md
- exercises/practice/pig-latin/.approaches/strchr-strstr-strtok/content.md
- exercises/practice/queen-attack/.approaches/helper-functions/content.md
- exercises/practice/scrabble-score/.approaches/array-lookup/content.md
- exercises/practice/scrabble-score/.approaches/switch-statement/content.md
- exercises/practice/sieve/.approaches/array-of-ones-and-zeros/content.md
In line with Exercism's spec, we're ensuring that all admonition fences are demarcated with four tildes (`~~~~`) across all repositories. We will be following up with an org-wide script that can be used to keep this consistent. [Problem Specifications](https://github.com/exercism/problem-specifications) has already been updated.
We'll automatically merge this a week from now, but feel free to merge beforehand!
- Spec: https://exercism.org/docs/building/markdown/markdown#h-special-blocks-sometimes-called-admonitions
- Meta issue: https://github.com/exercism/exercism/issues/6705
> Convert backtick (`) admonition fences to tildes (~)

- exercises/shared/.docs/tests.md
Specifically for the HELP.md file build for `exercism download`
The text was taken from docs/TESTS.md
Closes #921
> update the shared docs tests doc for memcheck

- config.json
- exercises/practice/gigasecond/.docs/instructions.append.md
- exercises/practice/gigasecond/.meta/example.c
- exercises/practice/gigasecond/.meta/example.h
- exercises/practice/gigasecond/gigasecond.h
- exercises/practice/gigasecond/test_gigasecond.c
I'm not terribly experienced in C. Have I implemented an OK way to handle strings without malloc/free?
Closes #924
> Rework gigasecond to be slightly more challenging

- exercises/practice/beer-song/test_beer_song.c
The empty line assertion has the arguments backwards (actual is in place of expected) which causes a confusing error message.
> test_beer_song.c - Fix assertion

- exercises/practice/word-count/test_word_count.c
- exercises/practice/word-count/word_count.h
This PR addresses issue #931 by sorting the expected and actual lists of word_count_word_t prior to comparing them.
> sorts solutions prior to check

- config.json
- exercises/practice/kindergarten-garden/.docs/instructions.md
- exercises/practice/kindergarten-garden/.meta/config.json
- exercises/practice/kindergarten-garden/.meta/example.c
- exercises/practice/kindergarten-garden/.meta/example.h
- exercises/practice/kindergarten-garden/.meta/tests.toml
- exercises/practice/kindergarten-garden/kindergarten_garden.c
- exercises/practice/kindergarten-garden/kindergarten_garden.h
- exercises/practice/kindergarten-garden/makefile
- exercises/practice/kindergarten-garden/test-framework/unity.c
- exercises/practice/kindergarten-garden/test-framework/unity.h
- exercises/practice/kindergarten-garden/test-framework/unity_internals.h
- exercises/practice/kindergarten-garden/test_kindergarten_garden.c
This adds `kindergarten-garden` from #940's list.
> Add kindergarten-garden (#940)

- bin/run-tests
- config.json
- exercises/practice/pop-count/.docs/instructions.md
- exercises/practice/pop-count/.docs/introduction.md
- exercises/practice/pop-count/.meta/config.json
- exercises/practice/pop-count/.meta/example.c
- exercises/practice/pop-count/.meta/example.h
- exercises/practice/pop-count/.meta/tests.toml
- exercises/practice/pop-count/makefile
- exercises/practice/pop-count/pop_count.c
- exercises/practice/pop-count/pop_count.h
- exercises/practice/pop-count/test-framework/unity.c
- exercises/practice/pop-count/test-framework/unity.h
- exercises/practice/pop-count/test-framework/unity_internals.h
- exercises/practice/pop-count/test_pop_count.c
Implements one of the missing exercises from #940.
> Add pop-count (#940)

- bin/run-tests
- docs/CONTRIBUTING.md
BSD sed requires an argument with `-i` (backup file extension, disabling
backup file creation by providing an empty string; this is the default for GNU
sed when `-i` is specified without an argument).
Further, `/bin/bash` shipping with macOS 14 doesn't like `${*}` when the
argument list is empty (at least in the context it is used in `run-tests`).
The fix of having a distinct message for the case where `${*}` is empty also
improves the behavior for cases where a version of Bash is used that does not
complain about an empty `${*}`.
This has been tested on macOS Sonoma 14.3, but probably also applies to earlier
versions.
> Fix run-test for macOS standard tools

- exercises/practice/raindrops/.approaches/config.json
- exercises/practice/raindrops/.approaches/data-driven/content.md
- exercises/practice/raindrops/.approaches/data-driven/snippet.txt
- exercises/practice/raindrops/.approaches/if-statements/content.md
- exercises/practice/raindrops/.approaches/if-statements/snippet.txt
- exercises/practice/raindrops/.approaches/introduction.md
- exercises/practice/raindrops/.approaches/sprintf/content.md
- exercises/practice/raindrops/.approaches/sprintf/snippet.txt
Add some approaches to the Raindrops exercise in the C language track.
* Create config.json
* Create introduction.md
* Add a new approach using if statements
- Create snipptet.txt
- Create content.md
* Add a new approach using the sprintf function
- Create snipptet.txt
- Create content.md
* Add a new approach using data-driven programming
- Create snipptet.txt
- Create content.md
See also: https://forum.exercism.org/t/raindrops-dig-deeper-approaches/9520.
> Raindrops approaches

- config.json
- exercises/practice/protein-translation/.docs/instructions.md
- exercises/practice/protein-translation/.meta/config.json
- exercises/practice/protein-translation/.meta/example.c
- exercises/practice/protein-translation/.meta/example.h
- exercises/practice/protein-translation/.meta/tests.toml
- exercises/practice/protein-translation/makefile
- exercises/practice/protein-translation/protein_translation.c
- exercises/practice/protein-translation/protein_translation.h
- exercises/practice/protein-translation/test-framework/unity.c
- exercises/practice/protein-translation/test-framework/unity.h
- exercises/practice/protein-translation/test-framework/unity_internals.h
- exercises/practice/protein-translation/test_protein_translation.c
Related to https://github.com/exercism/c/issues/940
Note that protein-translation is the #48in24 exercise for next week, so I'd like to get this in prior to Tuesday, Feb. 13th if possible.
> Add protein-translation

- config.json
- exercises/practice/knapsack/.docs/instructions.md
- exercises/practice/knapsack/.meta/config.json
- exercises/practice/knapsack/.meta/example.c
- exercises/practice/knapsack/.meta/example.h
- exercises/practice/knapsack/.meta/tests.toml
- exercises/practice/knapsack/knapsack.c
- exercises/practice/knapsack/knapsack.h
- exercises/practice/knapsack/makefile
- exercises/practice/knapsack/test-framework/unity.c
- exercises/practice/knapsack/test-framework/unity.h
- exercises/practice/knapsack/test-framework/unity_internals.h
- exercises/practice/knapsack/test_knapsack.c
Related to https://github.com/exercism/c/issues/940
> Add knapsack

- exercises/practice/zebra-puzzle/.meta/example.c
- exercises/practice/zebra-puzzle/.meta/example.h
- exercises/practice/zebra-puzzle/test_zebra_puzzle.c
- exercises/practice/zebra-puzzle/zebra_puzzle.h
Following the discussion at <https://github.com/exercism/c/pull/959#discussion_r1501899860>, this PR changes the API of the solution. Instead of two formally independent functions for the two sub-tasks the tests now require a single function that returns a `struct` with the two answers. That should reduce the boilerplate that students will have to write.
It also improves some small details of the example solution.
> Improve the zebra-puzzle.

- exercises/practice/raindrops/.approaches/data-driven/content.md
- exercises/practice/raindrops/.approaches/if-statements/content.md
- exercises/practice/raindrops/.approaches/introduction.md
- exercises/practice/raindrops/.approaches/sprintf/content.md
- exercises/practice/raindrops/.meta/example.c
- exercises/practice/raindrops/.meta/example.h
- exercises/practice/raindrops/raindrops.h
Return type is amended from `char*` to `void` for the function `convert(char result[], int drops)`
Fixes #968
> Amend the return type of function in `raindrop`

- config.json
This definitely isn't perfect, but I think it's a pretty significant improvement over our current state. What I did was:
- Re-assigned difficulties based on gut feel (from my own experience and by looking at our solutions), completion percentages (see https://exercism.org/tracks/c/build), and topics covered (for example, anything with memory management was bumped up to at least a 4 or 5... we had several at 1 and 2 :neutral_face:)
- Ordered all of the exercises by difficulty
- Within the lower difficulty levels, I ordered exercises such that not too much was introduced at a time.
As a next step, I think we can pick a difficulty cut-off point and start adding more complete skeletons to earlier exercises. This would address:
- https://github.com/exercism/c/issues/911
- …
> Re-rank and re-order exercises

- config.json
- exercises/practice/dnd-character/.docs/instructions.md
- exercises/practice/dnd-character/.docs/introduction.md
- exercises/practice/dnd-character/.meta/config.json
- exercises/practice/dnd-character/.meta/example.c
- exercises/practice/dnd-character/.meta/example.h
- exercises/practice/dnd-character/.meta/tests.toml
- exercises/practice/dnd-character/dnd_character.c
- exercises/practice/dnd-character/dnd_character.h
- exercises/practice/dnd-character/makefile
- exercises/practice/dnd-character/test-framework/unity.c
- exercises/practice/dnd-character/test-framework/unity.h
- exercises/practice/dnd-character/test-framework/unity_internals.h
- exercises/practice/dnd-character/test_dnd_character.c
Implements a missing exercise from #48in24 (#940).
> Add exercise dnd-character

- README.md
The image of the CI build status was broken. This fixes it.
> Fix CI build status badge

- docs/CONTRIBUTING.md
This link is causing an error 404 in https://github.com/exercism/c/actions/runs/12191782761/job/34011266814?pr=1024.
> Update broken link in CONTRIBUTING.md

- exercises/practice/protein-translation/.meta/config.json
- exercises/practice/protein-translation/.meta/tests.toml
- exercises/practice/protein-translation/test_protein_translation.c
This pull request updates the test suite for the **Protein-Translation** exercise to sync it with the problem specification repository.
> Updating tests for Protein-Translation

- exercises/practice/bob/.meta/config.json
- exercises/practice/bob/.meta/tests.toml
- exercises/practice/bob/test_bob.c
This pull request updates the test suite for the **Bob** exercise to sync it with the problem specification repository. This follows the prior heads-up via [PR](https://github.com/exercism/c/pull/1028).
> Adding tests to Bob exercise

- exercises/practice/phone-number/.meta/config.json
- exercises/practice/phone-number/.meta/tests.toml
I've synced the `toml` file with the problem specification repository. Currently, the tests are functioning as expected, with the program returning a "0000...0" phone number for invalid inputs. However, according to the `canonical-data.json` file in the `problem-specification` repository, the suggested behavior is for the program to throw an error when an invalid phone number is passed as an argument.
To align with the problem specification, we would need to:
1. Add the error handling where required in the test file.
2. Update the example answers accordingly.
Since the program is currently working with the existing approach (returning "0000...0"), I'm asking whether you'd prefer to proceed with the new specification of throwing an error for invalid phone numbers. Let me know how you'd …
> Updating tests for phone-number

- exercises/practice/pig-latin/.meta/config.json
- exercises/practice/pig-latin/.meta/tests.toml
- exercises/practice/pig-latin/test_pig_latin.c
This pull request updates the test suite for the **Pig-Latin** exercise to sync it with the problem specification repository.
> Updating tests for Pig-Latin

- exercises/practice/roman-numerals/.meta/config.json
- exercises/practice/roman-numerals/.meta/example.c
- exercises/practice/roman-numerals/.meta/tests.toml
- exercises/practice/roman-numerals/test_roman_numerals.c
This pull request updates the test suite for the **Roman-Numerals** exercise to sync it with the problem specification repository and rearranges the existing tests to follow numerical order.
> Updating new tests and rearranging tests for Roman-Numerals

- exercises/practice/palindrome-products/.meta/config.json
- exercises/practice/palindrome-products/.meta/example.c
- exercises/practice/palindrome-products/.meta/tests.toml
- exercises/practice/palindrome-products/test_palindrome_products.c
This pull request updates the test suite for the **Palindrome-Products** exercise to sync it with the problem specification repository.
> Updating tests for palindrome-products

- exercises/practice/anagram/.meta/config.json
- exercises/practice/anagram/.meta/tests.toml
- exercises/practice/anagram/test_anagram.c
This pull request updates the test suite for the **Anagram** exercise to sync it with the problem specification repository.
> Updating tests for Anagram

- exercises/practice/protein-translation/.meta/example.c
- exercises/practice/protein-translation/.meta/example.h
- exercises/practice/protein-translation/protein_translation.h
- exercises/practice/protein-translation/test_protein_translation.c
According to how the exercise's stub files and test files are currently written, one could assume that from a single RNA strand multiple proteins are decoded. In the example files, stub files and test file I made a few minor changes to the names of types, variables, etc. to more accurately reflect biological terminology, e.g., one 3-letter codon corresponds to one amino acid (Methionine, Phenylalanine, etc.), and one RNA sequence corresponds to one protein, which is made out of several amino acids. Feedback on this PR will be greatly appreciated.
> Exercises - Protein Translation - Patch 1 (to clarify biological terminology)

- config.json
- exercises/practice/variable-length-quantity/.docs/instructions.md
- exercises/practice/variable-length-quantity/.meta/config.json
- exercises/practice/variable-length-quantity/.meta/example.c
- exercises/practice/variable-length-quantity/.meta/example.h
- exercises/practice/variable-length-quantity/.meta/tests.toml
- exercises/practice/variable-length-quantity/makefile
- exercises/practice/variable-length-quantity/test-framework/unity.c
- exercises/practice/variable-length-quantity/test-framework/unity.h
- exercises/practice/variable-length-quantity/test-framework/unity_internals.h
- exercises/practice/variable-length-quantity/test_variable_length_quantity.c
- exercises/practice/variable-length-quantity/variable_length_quantity.c
- exercises/practice/variable-length-quantity/variable_length_quantity.h
Hello,
A few days ago I was trying to create a encoder/decoder for SQLite's `Varint`s. Instead of implementing the tests by hand, I searched for already implemented tests.
I stumbled upon _Exercism_ and the VLQ exercise in Python. As it was not implemented in C, I decided to port it. Hopefully someone will find it fun/useful as well.
Note that this is my first time contributing to (or even using) Exercism.
The test generation was automated using the `canonical-data.json` as input. It's a relatively specific script (and implemented in Perl), but I'm attaching here still:
[gen-tests.pl.gz](https://github.com/user-attachments/files/20422427/gen-tests.pl.gz) (gzip-ed so that github accepts it)
I have a couple questions for the reviewers:
- The `example.c` may no be very reader-friendly. Is it …
> [Exercise] implement variable-length-quantity exercise

- .github/workflows/checks.yml
The lychee checks have been failing often for gnu.org and now they seem to fail 100% for GitHub links. I tried updating the lychee action with the same result and found [an issue](https://github.com/lycheeverse/lychee/issues/733) that seems to describe a similar issue that is blamed on a dependency of lychee that can't be easily fixed.
It seems like this check has gotten to be more trouble than it's worth. What does everyone think about disabling it? @wolf99 @siebenschlaefer
> Disable lychee-action

- config.json
- exercises/practice/intergalactic-transmission/.docs/instructions.md
- exercises/practice/intergalactic-transmission/.docs/introduction.md
- exercises/practice/intergalactic-transmission/.meta/config.json
- exercises/practice/intergalactic-transmission/.meta/example.c
- exercises/practice/intergalactic-transmission/.meta/example.h
- exercises/practice/intergalactic-transmission/.meta/tests.toml
- exercises/practice/intergalactic-transmission/intergalactic_transmission.c
- exercises/practice/intergalactic-transmission/intergalactic_transmission.h
- exercises/practice/intergalactic-transmission/makefile
- exercises/practice/intergalactic-transmission/test-framework/unity.c
- exercises/practice/intergalactic-transmission/test-framework/unity.h
- exercises/practice/intergalactic-transmission/test-framework/unity_internals.h
- exercises/practice/intergalactic-transmission/test_intergalactic_transmission.c
Reviewed this over at [arm64-assembly](https://github.com/exercism/arm64-assembly/pull/161) and think it's a nice exercise, so I figured I'd add it here!
The test file is taken from the arm64 track with minor modifications. Over there we have generators for all test files. What would other reviewers think of introducing something like that here as well?
> Add intergalactic-transmission

- exercises/practice/beer-song/.meta/example.c
- exercises/practice/clock/.meta/example.c
- exercises/practice/nucleotide-count/.meta/example.c
- exercises/practice/raindrops/.meta/example.c
- exercises/practice/run-length-encoding/.meta/example.c
- exercises/practice/series/.meta/example.c
`sprintf` has been deprecated on macOS and a warning is issued when using it. `-Werror` turns the warning into an error, consequently tests don't pass on macOS. This fixes this by using `snprintf` instead.
> Use snprintf instead of sprintf

- .github/workflows/test.yml
gcc on arm64 macOS does not support sanitizers yet, so we only build with Apple Clang there.
> Add macos-15 CI job

- exercises/shared/.docs/help.md
Including this in the `exercises/shared/.docs/help.md` file also adds it to the help text in the online editor (see screenshot in [this discord thread](https://discord.com/channels/854117591135027261/1414640905838792745/1414640905838792745)). Students cannot submit incomplete solutions from the online editor, so this advice is wrong.
For students working locally, the HELP.md text that gets generated for `exercism download` already includes text about submitting incomplete solutions.
* how HELP.md [gets generated](https://github.com/exercism/website/blob/d71ef0744c90fd43b4d167b173f10d9c9ca68fb9/app/commands/solution/generate_help_file.rb#L31)
* the [submit text](https://github.com/exercism/website/blob/d71ef0744c90fd43b4d167b173f10d9c9ca68fb9/config/locales/exercises/en.yml#L9)
* a …
> Remove "submitting incomplete solutions" from help doc
